USE [OGMA_Test]
GO

/****** Object:  Table [dbo].[OP_ref_insert]    Script Date: 2021-05-19 12:03:31 PM ******/
CREATE PROC InsertOPRef(
    @ref_table varchar(64),
    @ref_value varchar(64),
    @language varchar(20),
    @ref_desc varchar(max))
AS
set nocount on
IF EXISTS(SELECT 'TRUE' FROM [dbo].[OP_Ref] WHERE @ref_table = [dbo].[OP_Ref].ref_table AND @ref_value =[dbo].[OP_Ref].ref_value AND @language = [dbo].[OP_Ref].language)
    BEGIN
    print('The Entry Already Exists Update Description')
    UPDATE [dbo].[OP_Ref] SET ref_desc = @ref_desc WHERE @ref_table = [dbo].[OP_Ref].ref_table AND
    @ref_value =[dbo].[OP_Ref].ref_value AND @language = [dbo].[OP_Ref].language
    END

ELSE
 BEGIN
    print('Entry added')
    INSERT into [dbo].[OP_Ref] (ref_table,ref_value, language, ref_desc)
    values (@ref_table,@ref_value,@language,@ref_desc)
END
GO


EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H1', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 1 (Haut)'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H1', @language = 'En', @ref_desc = 'Organization Level 1 (Top)'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H2', @language = 'En', @ref_desc = 'Organization Level 2'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H2', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 2'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H3', @language = 'En', @ref_desc = 'Organization Level 3'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H3', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 3'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H4', @language = 'En', @ref_desc = 'Organization Level 4'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H4', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 4'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H5', @language = 'En', @ref_desc = 'Organization Level 5'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H5', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 5'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H6', @language = 'En', @ref_desc = 'Organization'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H6', @language = 'Fr', @ref_desc = 'Organisation'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H1', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 1 (Haut)'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H1', @language = 'En', @ref_desc = 'Organization Level 1 (Top)'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H2', @language = 'En', @ref_desc = 'Organization Level 2'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H2', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 2'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H3', @language = 'En', @ref_desc = 'Organization Level 3'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H3', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 3'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H4', @language = 'En', @ref_desc = 'Organization Level 4'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H4', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 4'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H5', @language = 'En', @ref_desc = 'Organization Level 5'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H5', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 5'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H6', @language = 'En', @ref_desc = 'Organization'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H6', @language = 'Fr', @ref_desc = 'Organisation'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG001', @language = 'En', @ref_desc = 'OPG 001 Time Series Measures'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG001', @language = 'Fr', @ref_desc = 'OPG 001 Mesures de Séries Chronologiques'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG010', @language = 'En', @ref_desc = 'OPG010 SanKey Series'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG010', @language = 'Fr', @ref_desc = 'OPG010 Série SanKey'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Parameters', @language = 'En', @ref_desc = 'Parameters'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Parameters',@language = 'Fr', @ref_desc = 'Paramètres'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph', @language = 'En', @ref_desc = 'Graph'
EXEC InsertOPRef @ref_table  = 'Labels', @ref_value = 'LBL_Graph', @language = 'Fr', @ref_desc = 'Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphing_App', @language = 'En', @ref_desc = 'Graphing App'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphing_App', @language = 'Fr', @ref_desc = 'Application Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy', @language = 'En', @ref_desc = 'Hierarchy'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy', @language = 'Fr', @ref_desc = 'Hiérarchie'
Exec InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Level_Filter', @language = 'En', @ref_desc = 'Level Filter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Level_Filter', @language = 'Fr', @ref_desc = 'Filtre de Niveau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Specific_Item', @language = 'En', @ref_desc = 'Specific Item'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Specific_Item', @language = 'Fr', @ref_desc = 'Article Spécifique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select', @language = 'En', @ref_desc = 'Select'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select', @language = 'Fr', @ref_desc = 'Sélectionner'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_Range', @language = 'En', @ref_desc = 'Select Range'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_Range', @language = 'Fr', @ref_desc = 'Sélectionnez la plage'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Timeframe', @language = 'En', @ref_desc = 'TimeFrame'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Timeframe', @language = 'Fr', @ref_desc = 'Plage de Temps'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Year', @language = 'En', @ref_desc = 'Year'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Year', @language = 'Fr', @ref_desc = 'Année'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Year',@language = 'En', @ref_desc = 'Fiscal Year'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Year', @language = 'Fr', @ref_desc = 'Exercice fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Month', @language = 'En', @ref_desc = 'Month'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Month', @language = 'Fr', @ref_desc = 'Mois'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Week', @language = 'En', @ref_desc = 'Week'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Week', @language = 'Fr', @ref_desc = 'semaine'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarter', @language = 'En', @ref_desc = 'Quarter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarter', @language = 'Fr', @ref_desc = 'Trimestre'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Type', @language = 'En', @ref_desc = 'Graph Type'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Type', @language = 'Fr', @ref_desc = 'Type de Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis', @language = 'En', @ref_desc = 'X-Axis'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis', @language = 'Fr', @ref_desc = 'Axe X'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis', @language = 'En', @ref_desc = 'Y-Axis'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis', @language = 'Fr', @ref_desc = 'Axe Y'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bubble', @language = 'En', @ref_desc = 'Bubble'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bubble', @language = 'Fr', @ref_desc = 'Bulle'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Line', @language = 'En', @ref_desc = 'Line'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Line', @language = 'Fr', @ref_desc = 'Linéaire'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bar', @language = 'En', @ref_desc = 'Bar'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bar', @language = 'Fr', @ref_desc = 'Barres'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Scatter', @language = 'En', @ref_desc = 'Scatter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Scatter', @language = 'Fr', @ref_desc = 'Dispersion'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Partial_Period', @language = 'En', @ref_desc = 'Partial Period'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Partial_Period', @language = 'Fr', @ref_desc = 'Période Partielle'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Options', @language = 'En', @ref_desc = 'Graph Options'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Options', @language = 'Fr', @ref_desc = 'Options de Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Revert', @language = 'En', @ref_desc = 'Revert'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Revert', @language = 'Fr', @ref_desc = 'Revenir'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_To_Top', @language = 'En', @ref_desc = 'To Top'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_To_Top', @language = 'Fr', @ref_desc = 'Au Début'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_In_Dropdown', @language = 'En', @ref_desc = 'Graph All in Dropdown'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_In_Dropdown', @language = 'Fr', @ref_desc = 'Graphique Tout dans la Liste Déroulante'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Time', @language = 'En', @ref_desc = 'Time'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Time',@language = 'Fr', @ref_desc = 'Temps'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Names', @language = 'En', @ref_desc = 'Variable Names'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Names', @language = 'Fr', @ref_desc = 'Noms de Variables'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children', @language = 'En', @ref_desc = 'Children'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children', @language = 'Fr', @ref_desc = 'Enfants'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_TRUE',@language = 'En', @ref_desc = 'TRUE'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_TRUE',@language = 'Fr', @ref_desc = 'Vrai'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_FALSE',@language = 'En', @ref_desc = 'FALSE'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_FALSE',@language = 'Fr', @ref_desc = 'Faux'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_New',@language = 'En', @ref_desc = 'New'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_New',@language = 'Fr', @ref_desc = 'Nouveau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_View',@language = 'En', @ref_desc = 'View'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_View',@language = 'Fr', @ref_desc = 'Vue'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data',@language = 'En', @ref_desc = 'Data'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data',@language = 'Fr', @ref_desc = 'Données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Set',@language = 'En', @ref_desc = 'Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Set',@language = 'Fr', @ref_desc = 'Base de données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Customize',@language = 'En', @ref_desc = 'Customize'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Customize',@language = 'Fr', @ref_desc = 'Personnaliser'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Graph_Title',@language = 'En', @ref_desc = 'Enter Graph Title'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Graph_Title',@language = 'Fr', @ref_desc = 'Entrez le Titre du Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_Selection''s_Children',@language = 'En',@ref_desc = 'Hierarchy Selection''s Children'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_Selection''s_Children',@language = 'Fr',@ref_desc = 'Enfants de la Sélection de Hiérarchie'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Table',@language = 'En', @ref_desc = 'Table'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Table',@language = 'Fr', @ref_desc = 'Tableau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_One_Name',@language = 'En', @ref_desc = 'Hierarchy One Name'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_One_Name',@language = 'Fr', @ref_desc = 'Hiérarchie un Nom'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Name',@language = 'En', @ref_desc = 'Variable Name'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Name',@language = 'Fr', @ref_desc = 'Nom de Variable'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Name_Qualifier',@language = 'En', @ref_desc = 'Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Name_Qualifier',@language = 'Fr', @ref_desc = 'Qualificateur de Nom de Variable'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Name_Sub_Qualifier',@language = 'En', @ref_desc = 'Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Name_Sub_Qualifier',@language = 'Fr', @ref_desc = 'Sous-Qualificateur de Nom de Variable'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date_Of_Event',@language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date_Of_Event',@language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Calendar_Entry_Type',@language = 'En', @ref_desc = 'Calendar Entry Type'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Calendar_Entry_Type',@language = 'Fr', @ref_desc = 'Type d''entrée d''Agenda'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Year_Of_Event',@language = 'En', @ref_desc = 'Year of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Year_Of_Event',@language = 'Fr', @ref_desc = 'Année de l''événement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Month_Of_Event',@language = 'En', @ref_desc = 'Month of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Month_Of_Event',@language = 'Fr', @ref_desc = 'Mois de l''événement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Week_Of_Event',@language = 'En', @ref_desc = 'Week of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Week_Of_Event',@language = 'Fr', @ref_desc = 'Semaine d''événement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Year_Of_Event',@language = 'En', @ref_desc = 'Fiscal Year of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Year_Of_Event',@language = 'Fr', @ref_desc = 'Année Financière de l''événement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Quarter',@language = 'En', @ref_desc = 'Fiscal Quarter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Quarter',@language = 'Fr', @ref_desc = 'Trimestre Fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Month_Of_Event',@language = 'En', @ref_desc = 'Fiscal Month of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Month_Of_Event',@language = 'Fr', @ref_desc = 'Mois Fiscal de l''événement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Week_Of_Event',@language = 'En', @ref_desc = 'Fiscal Week of Event'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Week_Of_Event',@language = 'Fr', @ref_desc = 'Semaine Fiscale de l''événement'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Julian_Day',@language = 'En', @ref_desc = 'Julian Day'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Julian_Day',@language = 'Fr', @ref_desc = 'Julian Day'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Activity_Event_Id',@language = 'En', @ref_desc = 'Activity Event Id'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Activity_Event_Id',@language = 'Fr', @ref_desc = 'ID d''événement d''Activité'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Measure_Value',@language = 'En', @ref_desc = 'Measure Value'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Measure_Value',@language = 'Fr', @ref_desc = 'Mesurer la Valeur'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Measure_Type',@language = 'En', @ref_desc = 'Measure Type'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Measure_Type',@language = 'Fr', @ref_desc = 'Type de Mesure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Toggle_Columns',@language = 'En', @ref_desc = 'Toggle Columns'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Toggle_Columns',@language = 'Fr', @ref_desc = 'Basculer les Colonnes'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Box_Plot',@language = 'En', @ref_desc = 'Box Plot'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Box_Plot',@language = 'Fr', @ref_desc = 'Boîte à Moustaches'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Show_Data_Points',@language = 'En', @ref_desc = 'Show Data Points'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Show_Data_Points',@language = 'Fr', @ref_desc = 'Afficher les Points de Données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Horizontal',@language = 'En', @ref_desc = 'Horizontal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Horizontal',@language = 'Fr', @ref_desc = 'Horizontal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Vertical',@language = 'En', @ref_desc = 'Vertical'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Vertical',@language = 'Fr', @ref_desc = 'Vertical'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphed_Variables',@language = 'En', @ref_desc = 'Graphed Variables'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphed_Variables',@language = 'Fr', @ref_desc = 'Variables Graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Median',@language = 'En', @ref_desc = 'Median'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Median',@language = 'Fr', @ref_desc = 'Médiane'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Min',@language = 'En', @ref_desc = 'Min'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Min',@language = 'Fr', @ref_desc = 'Min'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Max',@language = 'En', @ref_desc = 'Max'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Max',@language = 'Fr', @ref_desc = 'Max'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Distribution',@language = 'En', @ref_desc = 'Distribution'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Distribution',@language = 'Fr', @ref_desc = 'Distribution'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Calendar_Type',@language = 'En', @ref_desc = 'Calendar Type'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Calendar_Type',@language = 'Fr', @ref_desc = 'Type de Calendrier'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Gregorian',@language = 'En', @ref_desc = 'Gregorian'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Gregorian',@language = 'Fr', @ref_desc = 'Grégorien'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal',@language = 'En', @ref_desc = 'Fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal',@language = 'Fr', @ref_desc = 'Fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_All_Time_Monthly',@language = 'En', @ref_desc = 'All-Time (Monthly)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_All_Time_Monthly',@language = 'Fr', @ref_desc = 'Tous les temps (mensuel)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Last',@language = 'En', @ref_desc = 'Last'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Last',@language = 'Fr', @ref_desc = 'Dernière'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Years',@language = 'En', @ref_desc = 'Year(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Years',@language = 'Fr', @ref_desc = 'Année(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Months',@language = 'En', @ref_desc = 'Month(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Months',@language = 'Fr', @ref_desc = 'Mois'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarters',@language = 'En', @ref_desc = 'Quarter(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarters',@language = 'Fr', @ref_desc = 'Trimestre(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Weeks',@language = 'En', @ref_desc = 'Week(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Weeks',@language = 'Fr', @ref_desc = 'Semaine(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Available',@language = 'En', @ref_desc = 'Available'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Available',@language = 'Fr', @ref_desc = 'Disponible'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Root''s_Children',@language = 'En', @ref_desc = 'Root''s Children'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Root''s_Children',@language = 'Fr', @ref_desc = 'Les Enfants de Root'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Back',@language = 'En', @ref_desc = 'Back'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Back',@language = 'Fr', @ref_desc = 'Arrière'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Top',@language = 'En', @ref_desc = 'Top'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Top',@language = 'Fr', @ref_desc = 'Haut'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axis_Measure',@language = 'En', @ref_desc = 'Axis Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axis_Measure',@language = 'Fr', @ref_desc = 'Mesure d''Axe'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Orientation',@language = 'En', @ref_desc = 'Graph Orientation'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Orientation',@language = 'Fr', @ref_desc = 'Orientation du Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Num_Of_Rows',@language = 'En', @ref_desc = '# of rows'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Num_Of_Rows',@language = 'Fr', @ref_desc = '# de Ros'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Filter_The_Table',@language = 'En', @ref_desc = 'How to Filter the Table'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Filter_The_Table',@language = 'Fr', @ref_desc = 'Comment Filtrer le Tableau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Hide_Columns',@language = 'En', @ref_desc = 'How to Hide Columns'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Hide_Columns',@language = 'Fr', @ref_desc = 'Comment Masquer les Colonnes'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date',@language = 'En', @ref_desc = 'Date'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date',@language = 'Fr', @ref_desc = 'Date'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Root',@language = 'En', @ref_desc = 'Root'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Root',@language = 'Fr', @ref_desc = 'l'' Orine'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Group_By',@language = 'En', @ref_desc = 'Group By'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Group_By',@language = 'Fr', @ref_desc = 'Par Groupe'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children_Of',@language = 'En', @ref_desc = 'Children '
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children_Of',@language = 'Fr', @ref_desc = 'Les Enfants de'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Tab',@language = 'En', @ref_desc = 'Tab'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Tab',@language = 'Fr', @ref_desc = 'Onglet'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs',@language = 'En', @ref_desc = 'Graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs',@language = 'Fr', @ref_desc = 'Graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_The_Graph',@language = 'En', @ref_desc = 'Save The Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_The_Graph',@language = 'Fr', @ref_desc = 'Enregistrer le graphique:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Graph',@language = 'En', @ref_desc = 'Select a saved graph:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Graph',@language = 'Fr', @ref_desc = 'Sélectionnez un graphique enregistré:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Graph',@language = 'En', @ref_desc = 'Delete a saved graph:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Graph',@language = 'Fr', @ref_desc = 'Supprimer un graphique enregistré:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Graph',@language = 'En', @ref_desc = 'Save Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Graph',@language = 'Fr', @ref_desc = 'Enregistrer le graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Delete',@language = 'En', @ref_desc = 'Confirm Delete'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Delete',@language = 'Fr', @ref_desc = 'Confirmation de la Suppression'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Dashboard_Title',@language = 'En', @ref_desc = 'Enter Dashboard Title'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Dashboard_Title',@language = 'Fr', @ref_desc = 'Entrez le titre du tableau de bord'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Dashboard',@language = 'En', @ref_desc = 'Save Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Dashboard',@language = 'Fr', @ref_desc = 'Enregistrez le tableau de bord'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Dashboard',@language = 'En', @ref_desc = 'Delete a saved dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Dashboard',@language = 'Fr', @ref_desc = 'Supprimer un tableau de bord enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboards_Require_A_Title_To_Be_Saved',@language = 'En', @ref_desc = 'Dashboards require a title to be saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboards_Require_A_Title_To_Be_Saved',@language = 'Fr', @ref_desc = 'Les tableaux de bord nécessitent un titre pour être enregistrés'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_Siblings',@language = 'En', @ref_desc = 'Graph All Siblings'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_Siblings',@language = 'Fr', @ref_desc = 'Graphique de tous les frères et sœurs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Data_Found',@language = 'En', @ref_desc = 'No Data Found'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Data_Found',@language = 'Fr', @ref_desc = 'Base de Données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs_Require_A_Title_To_Be_Saved',@language = 'En', @ref_desc = 'Graphs require a title to be saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs_Require_A_Title_To_Be_Saved',@language = 'Fr', @ref_desc = 'Les graphiques nécessitent un titre pour être enregistrés'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Graph_Has_Been_Saved',@language = 'En', @ref_desc = 'The graph has been saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Graph_Has_Been_Saved',@language = 'Fr', @ref_desc = 'Le graphique a été enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Graph_With_This_Title_Already_Exists',@language = 'En', @ref_desc = 'A saved graph with this title already exists'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Graph_With_This_Title_Already_Exists',@language = 'Fr', @ref_desc = 'Un graphique enregistré avec ce titre existe déjà'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Dashboard_Has_Been_Saved',@language = 'En', @ref_desc = 'The dashboard has been saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Dashboard_Has_Been_Saved',@language = 'Fr', @ref_desc = 'Le tableau de bord a été enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboard_Must_Not_Be_Empty',@language = 'En', @ref_desc = 'Dashboard must not be empty'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboard_Must_Not_Be_Empty',@language = 'Fr', @ref_desc = 'Le tableau de bord ne doit pas être vide'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Dashboard_With_This_Title_Already_Exists',@language = 'En', @ref_desc = 'A saved dashboard with this title already exists'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Dashboard_With_This_Title_Already_Exists',@language = 'Fr', @ref_desc = 'Un tableau de bord enregistré avec ce titre existe déjà'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Saved_Graphs_Already_Exist_For',@language = 'En', @ref_desc = 'Saved graphs already exist for'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Saved_Graphs_Already_Exist_For',@language = 'Fr', @ref_desc = 'Des graphiques enregistrés existent déjà pour'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Dashboard',@language = 'En', @ref_desc = 'Select a saved dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Dashboard',@language = 'Fr', @ref_desc = 'Sélectionnez un tableau de bord enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Save_Attempt',@language = 'En', @ref_desc = 'Cancel save attempt'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Save_Attempt',@language = 'Fr', @ref_desc = 'Annuler la tentative de sauvegarde'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard',@language = 'En', @ref_desc = 'Overwrite dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard',@language = 'Fr', @ref_desc = 'Écraser le tableau de bord'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graph',@language = 'En', @ref_desc = 'and the graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graph',@language = 'Fr', @ref_desc = 'et le graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graphs',@language = 'En', @ref_desc = 'and the graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graphs',@language = 'Fr', @ref_desc = 'et les graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graphs',@language = 'En', @ref_desc = 'Overwrite Graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graphs',@language = 'Fr', @ref_desc = 'Écraser les graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Reset_Attempt',@language = 'En', @ref_desc = 'Cancel reset attempt'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Reset_Attempt',@language = 'Fr', @ref_desc = 'Annuler la tentative de réinitialisation'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Sankey',@language = 'En', @ref_desc = 'Sankey'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Sankey',@language = 'Fr', @ref_desc = 'Fr: Saey'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In6',@language = 'En', @ref_desc = '150+'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In5',@language = 'En', @ref_desc = '121-150'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In4',@language = 'En', @ref_desc = '91-120'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In3',@language = 'En', @ref_desc = '61-90'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In2',@language = 'En', @ref_desc = '31-60'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In1',@language = 'En', @ref_desc = 'LT 31'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End6',@language = 'En', @ref_desc = 'Cpltd 150+'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End5',@language = 'En', @ref_desc = 'Cpltd 121-150'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End4',@language = 'En', @ref_desc = 'Cpltd 91-120'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End3',@language = 'En', @ref_desc = 'Cpltd 61-90'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End2',@language = 'En', @ref_desc = 'Cpltd 31-60'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End1',@language = 'En', @ref_desc = 'Cpltd LT 31'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out6',@language = 'En', @ref_desc = 'Cont 150+'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out5',@language = 'En', @ref_desc = 'Cont 121-150'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out4',@language = 'En', @ref_desc = 'Cont 91-120'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out3',@language = 'En', @ref_desc = 'Cont 61-90'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out2',@language = 'En', @ref_desc = 'Cont 31-60'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out1',@language = 'En', @ref_desc = 'Cont LT 31'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In6_Long',@language = 'En', @ref_desc = 'Outstanding > 150 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In6_Long',@language = 'Fr', @ref_desc = 'Fr: Outstanding > 150 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In5_Long',@language = 'En', @ref_desc = 'Outstanding 121 - 150 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In5_Long',@language = 'Fr', @ref_desc = 'Fr: Outstanding 121 - 150 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In4_Long',@language = 'En', @ref_desc = 'Outstanding 91 - 120 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In4_Long',@language = 'Fr', @ref_desc = 'Fr: Outstanding 91 - 120 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In3_Long',@language = 'En', @ref_desc = 'Outstanding 61 - 90 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_In3_Long',@language = 'Fr', @ref_desc = 'Fr: Outstanding 61 - 90 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End2_Long',@language = 'En', @ref_desc = 'Completed 31 - 60 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End2_Long',@language = 'Fr', @ref_desc = 'Fr: Completed 31 - 60 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End1_Long',@language = 'En', @ref_desc = 'Completed < 31 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End1_Long',@language = 'Fr', @ref_desc = 'Fr: Completed < 31 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_New_Long',@language = 'En', @ref_desc = 'New in last 30 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_New_Long',@language = 'Fr', @ref_desc = 'Fr: New in last 30 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out6_Long',@language = 'En', @ref_desc = 'Continued In-Process > 150 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out6_Long',@language = 'Fr', @ref_desc = 'Fr: Continued In-Process > 150 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out3_Long',@language = 'En', @ref_desc = 'Continued In-Process 61 - 90 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out3_Long',@language = 'Fr', @ref_desc = 'Fr: Continued In-Process 61 - 90 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out2_Long',@language = 'En', @ref_desc = 'Continued In-Process 31 - 60 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out2_Long',@language = 'Fr', @ref_desc = 'Fr: Continued In-Process 31 - 60 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out1_Long',@language = 'En', @ref_desc = 'Continued In-Process < 31 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Out1_Long',@language = 'Fr', @ref_desc = 'Fr: Continued In-Process < 31 days'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End',@language = 'En', @ref_desc = 'Cpltd'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End',@language = 'Fr', @ref_desc = 'Fr: Cpltd'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End_Long',@language = 'En', @ref_desc = 'Completed'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_End_Long',@language = 'Fr', @ref_desc = 'Complété'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Refresh_Data_Set',@language = 'En', @ref_desc = 'Refresh Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Refresh_Data_Set',@language = 'Fr', @ref_desc = 'Fr: Refresh Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Data_Set_Load',@language = 'En', @ref_desc = 'Confirm Data Set Load'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Data_Set_Load',@language = 'Fr', @ref_desc = 'Fr: Confirm Data Set Load'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard_All_Unsaved_Changes_will_Be_Lost',@language = 'En', @ref_desc = 'Reset dashboard all unsaved changes will be lost'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard_All_Unsaved_Changes_will_Be_Lost',@language = 'Fr', @ref_desc = 'Réinitialiser le tableau de bord - toutes les modifications non enregistrées seront perdues'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis_Measure',@language = 'En', @ref_desc = 'X-Axis Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis_Measure',@language = 'Fr', @ref_desc = 'Mesure de l axe X'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis_Measure',@language = 'En', @ref_desc = 'Y-Axis Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis_Measure',@language = 'Fr', @ref_desc = 'Mesure de l axe Y'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size',@language = 'En', @ref_desc = 'Size'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size',@language = 'Fr', @ref_desc = 'Taille'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size_Measure',@language = 'En', @ref_desc = 'Size Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size_Measure',@language = 'Fr', @ref_desc = 'Mesure de la taille'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Animate_Over_Time',@language = 'En', @ref_desc = 'Animate Over Time'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Animate_Over_Time',@language = 'Fr', @ref_desc = 'Animer au fil du temps'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Accessed_On',@language = 'En', @ref_desc = 'Data accessed on'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Accessed_On',@language = 'Fr', @ref_desc = 'Données consultées le'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Refresh_Data_Set',@language = 'En', @ref_desc = 'Refresh Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Refresh_Data_Set',@language = 'Fr', @ref_desc = 'Actualiser lensemble de données'
GO

DROP PROC InsertOPRef
GO
---when we update it from a space to underscore it gives key errors
/*
UPDATE [dbo].[OP_Ref]
SET    ref_value = REPLACE(ref_value, ' ', '_')
WHERE  ref_value LIKE '%[ ]%'
go*/

IF OBJECT_ID('dbo.reftable') IS NOT NULL
    PRINT   'REFTABLE Procedure Exists'

ELSE
	BEGIN
		EXEC('
    Create Proc dbo.reftable

    as
	BEGIN
    Select * From [dbo].[OP_Ref]
		END')
	END
    GO
