USE [OGMA_Test]
GO

/****** Object:  Table [dbo].[OP_ref_insert]    Script Date: 2021-05-19 12:03:31 PM ******/
CREATE PROC InsertOPRef(
    @ref_table varchar(64),
    @ref_value varchar(64),
    @language varchar(20),
    @ref_desc varchar(max))
AS
set nocount on
IF EXISTS(SELECT 'TRUE' FROM [dbo].[OP_Ref] WHERE @ref_table = [dbo].[OP_Ref].ref_table AND @ref_value =[dbo].[OP_Ref].ref_value AND @language = [dbo].[OP_Ref].language)
    BEGIN
    print('The Entry Already Exists Update Description')
    UPDATE [dbo].[OP_Ref] SET ref_desc = @ref_desc WHERE @ref_table = [dbo].[OP_Ref].ref_table AND
    @ref_value =[dbo].[OP_Ref].ref_value AND @language = [dbo].[OP_Ref].language
    END

ELSE
 BEGIN
    print('Entry added')
    INSERT into [dbo].[OP_Ref] (ref_table,ref_value, language, ref_desc)
    values (@ref_table,@ref_value,@language,@ref_desc)
END
GO


EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H0', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 1 (Haut)'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H0', @language = 'En', @ref_desc = 'Organization Level 1 (Top)'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H1', @language = 'En', @ref_desc = 'Organization Level 2'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H1', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 2'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H2', @language = 'En', @ref_desc = 'Organization Level 3'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H2', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 3'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H3', @language = 'En', @ref_desc = 'Organization Level 4'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H3', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 4'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H4', @language = 'En', @ref_desc = 'Organization Level 5'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H4', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 5'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H5', @language = 'En', @ref_desc = 'Organization'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_H5', @language = 'Fr', @ref_desc = 'Organisation'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In6', @language = 'En', @ref_desc = '150+'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In5', @language = 'En', @ref_desc = '121-150'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In4', @language = 'En', @ref_desc = '91-120'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In3', @language = 'En', @ref_desc = '61-90'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In2', @language = 'En', @ref_desc = '31-60'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In1', @language = 'En', @ref_desc = 'LT 31'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_New', @language = 'En', @ref_desc = 'New'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out6', @language = 'En', @ref_desc = 'Cont 150+'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out5', @language = 'En', @ref_desc = 'Cont 121-150'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out4', @language = 'En', @ref_desc = 'Cont 91-120'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out3', @language = 'En', @ref_desc = 'Cont 61-90'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out2', @language = 'En', @ref_desc = 'Cont 31-60'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out1', @language = 'En', @ref_desc = 'Cont LT 31'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_End', @language = 'En', @ref_desc = 'Cpltd'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In6', @language = 'Fr', @ref_desc = '150+'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In5', @language = 'Fr', @ref_desc = '121-150'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In4', @language = 'Fr', @ref_desc = '91-120'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In3', @language = 'Fr', @ref_desc = '61-90'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In2', @language = 'Fr', @ref_desc = '31-60'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In1', @language = 'Fr', @ref_desc = 'LT 31'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_New', @language = 'Fr', @ref_desc = 'Nouveau'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out6', @language = 'Fr', @ref_desc = 'Fr: Cont 150+'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out5', @language = 'Fr', @ref_desc = 'Fr: Cont 121-150'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out4', @language = 'Fr', @ref_desc = 'Fr: Cont 91-120'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out3', @language = 'Fr', @ref_desc = 'Fr: Cont 61-90'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out2', @language = 'Fr', @ref_desc = 'Fr: Cont 31-60'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out1', @language = 'Fr', @ref_desc = 'Fr: Cont LT 31'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_End', @language = 'Fr', @ref_desc = 'Fr: Cpltd'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In6_Long', @language = 'En', @ref_desc = 'Outstanding > 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In5_Long', @language = 'En', @ref_desc = 'Outstanding 121 - 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In4_Long', @language = 'En', @ref_desc = 'Outstanding 91 - 120 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In3_Long', @language = 'En', @ref_desc = 'Outstanding 61 - 90 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In2_Long', @language = 'En', @ref_desc = 'Outstanding 31 - 60 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In1_Long', @language = 'En', @ref_desc = 'Outstanding < 31 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_New_Long', @language = 'En', @ref_desc = 'New in last 30 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out6_Long', @language = 'En', @ref_desc = 'Continued In-Process > 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out5_Long', @language = 'En', @ref_desc = 'Continued In-Process 121 - 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out4_Long', @language = 'En', @ref_desc = 'Continued In-Process 91 - 120 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out3_Long', @language = 'En', @ref_desc = 'Continued In-Process 61 - 90 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out2_Long', @language = 'En', @ref_desc = 'Continued In-Process 31 - 60 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out1_Long', @language = 'En', @ref_desc = 'Continued In-Process < 31 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_End_Long', @language = 'En', @ref_desc = 'Completed'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In6_Long', @language = 'Fr', @ref_desc = 'Fr: Outstanding > 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In5_Long', @language = 'Fr', @ref_desc = 'Fr: Outstanding 121 - 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In4_Long', @language = 'Fr', @ref_desc = 'Fr: Outstanding 91 - 120 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In3_Long', @language = 'Fr', @ref_desc = 'Fr: Outstanding 61 - 90 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In2_Long', @language = 'Fr', @ref_desc = 'Fr: Outstanding 31 - 60 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_In1_Long', @language = 'Fr', @ref_desc = 'Fr: Outstanding < 31 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_New_Long', @language = 'Fr', @ref_desc = 'Fr: New in last 30 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out6_Long', @language = 'Fr', @ref_desc = 'Fr: Continued In-Process > 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out5_Long', @language = 'Fr', @ref_desc = 'Fr: Continued In-Process 121 - 150 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out4_Long', @language = 'Fr', @ref_desc = 'Fr: Continued In-Process 91 - 120 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out3_Long', @language = 'Fr', @ref_desc = 'Fr: Continued In-Process 61 - 90 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out2_Long', @language = 'Fr', @ref_desc = 'Fr: Continued In-Process 31 - 60 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Out1_Long', @language = 'Fr', @ref_desc = 'Fr: Continued In-Process < 31 days'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_End_Long', @language = 'Fr', @ref_desc = 'Complété'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Node_HoverTemplate', @language = 'En', @ref_desc = '%VALUE% Documents %NODE%'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Node_HoverTemplate', @language = 'Fr', @ref_desc = 'Fr: %VALUE% Documents %NODE%'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Link_HoverTemplate', @language = 'En', @ref_desc = '%VALUE% Documents %SOURCE-NODE% became %TARGET-NODE%'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Link_HoverTemplate', @language = 'Fr', @ref_desc = 'Fr: %VALUE% Documents %SOURCE-NODE% became %TARGET-NODE%'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_OPG_Data_Set',            @language = 'En', @ref_desc = 'Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Variable_Name',           @language = 'En', @ref_desc = 'Document Type'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'En', @ref_desc = 'Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'En', @ref_desc = 'Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Date_Of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Date_of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'En', @ref_desc = 'Calendar Entry Type'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Year_of_Event',           @language = 'En', @ref_desc = 'Year of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Quarter',                 @language = 'En', @ref_desc = 'Quarter'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Month_of_Event',          @language = 'En', @ref_desc = 'Month of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Week_of_Event',           @language = 'En', @ref_desc = 'Week of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'En', @ref_desc = 'Fiscal Year of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'En', @ref_desc = 'Fiscal Quarter'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'En', @ref_desc = 'Fiscal Month of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'En', @ref_desc = 'Fiscal Week of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Julian_Day',              @language = 'En', @ref_desc = 'Julian Day of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Activity_Event_Id',       @language = 'En', @ref_desc = 'Document Control #'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Value',           @language = 'En', @ref_desc = 'Measure Value'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Type',            @language = 'En', @ref_desc = 'Measure Type'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Partial_Period',          @language = 'En', @ref_desc = 'Partial Period?'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Id',              @language = 'En', @ref_desc = 'Source Node #'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Fcn',             @language = 'En', @ref_desc = 'Function'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_MeasQual1',               @language = 'En', @ref_desc = 'Target Node #'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_MeasQual2',               @language = 'En', @ref_desc = 'Value'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_empty_column',            @language = 'En', @ref_desc = ' '
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Comment',                 @language = 'En', @ref_desc = 'Comment'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_OPG_Data_Set',            @language = 'Fr', @ref_desc = 'Fr: Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Variable_Name',           @language = 'Fr', @ref_desc = 'Fr: Document Type'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Date_Of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Date_of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'Fr', @ref_desc = 'Type d''entrée d''Agenda'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Year_of_Event',           @language = 'Fr', @ref_desc = 'Année de l''événement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Quarter',                 @language = 'Fr', @ref_desc = 'Trimestre'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Month_of_Event',          @language = 'Fr', @ref_desc = 'Mois de l''événement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Week_of_Event',           @language = 'Fr', @ref_desc = 'Semaine d''événement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'Fr', @ref_desc = 'Année Financière de l''événement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'Fr', @ref_desc = 'Trimestre Fiscal'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'Fr', @ref_desc = 'Mois Fiscal de l''événement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'Fr', @ref_desc = 'Semaine Fiscale de l''événement'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Julian_Day',              @language = 'Fr', @ref_desc = 'Fr: Julilan Day of Event'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Activity_Event_Id',       @language = 'Fr', @ref_desc = 'Fr: Document Control #'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Value',           @language = 'Fr', @ref_desc = 'Mesurer la Valeur'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Type',            @language = 'Fr', @ref_desc = 'Type de Mesure'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Partial_Period',          @language = 'Fr', @ref_desc = 'Période Partielle?'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Id',              @language = 'Fr', @ref_desc = 'Fr: Source Node #'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Measure_Fcn',             @language = 'Fr', @ref_desc = 'Fr: Function'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_MeasQual1',               @language = 'Fr', @ref_desc = 'Fr: Target Node #'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_MeasQual2',               @language = 'Fr', @ref_desc = 'Valeur'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_empty_column',            @language = 'Fr', @ref_desc = ' '
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Comment',                 @language = 'Fr', @ref_desc = 'Fr: Comment'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'En', @ref_desc = 'Hierarchy One Name'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'Fr', @ref_desc = 'Hiérarchie un Nom'

EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H0', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 1 (Haut)'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H0', @language = 'En', @ref_desc = 'Organization Level 1 (Top)'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H1', @language = 'En', @ref_desc = 'Organization Level 2'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H1', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 2'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H2', @language = 'En', @ref_desc = 'Organization Level 3'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H2', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 3'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H3', @language = 'En', @ref_desc = 'Organization Level 4'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H3', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 4'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H4', @language = 'En', @ref_desc = 'Organization Level 5'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H4', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 5'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H5', @language = 'En', @ref_desc = 'Organization'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_H5', @language = 'Fr', @ref_desc = 'Organisation'

EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_OPG_Data_Set',            @language = 'En', @ref_desc = 'Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Variable_Name',           @language = 'En', @ref_desc = 'Document Type'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'En', @ref_desc = 'Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'En', @ref_desc = 'Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Date_Of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Date_of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'En', @ref_desc = 'Calendar Entry Type'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Year_of_Event',           @language = 'En', @ref_desc = 'Year of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Quarter',                 @language = 'En', @ref_desc = 'Quarter'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Month_of_Event',          @language = 'En', @ref_desc = 'Month of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Week_of_Event',           @language = 'En', @ref_desc = 'Week of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'En', @ref_desc = 'Fiscal Year of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'En', @ref_desc = 'Fiscal Quarter'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'En', @ref_desc = 'Fiscal Month of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'En', @ref_desc = 'Fiscal Week of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Julian_Day',              @language = 'En', @ref_desc = 'Julian Day of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Activity_Event_Id',       @language = 'En', @ref_desc = 'Document Control #'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Measure_Value',           @language = 'En', @ref_desc = 'Measure Value'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Measure_Type',            @language = 'En', @ref_desc = 'Measure Type'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_OPG_Data_Set',            @language = 'Fr', @ref_desc = 'Fr: Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Variable_Name',           @language = 'Fr', @ref_desc = 'Fr: Document Type'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Date_Of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Date_of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'Fr', @ref_desc = 'Type d''entrée d''Agenda'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Year_of_Event',           @language = 'Fr', @ref_desc = 'Année de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Quarter',                 @language = 'Fr', @ref_desc = 'Trimestre'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Month_of_Event',          @language = 'Fr', @ref_desc = 'Mois de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Week_of_Event',           @language = 'Fr', @ref_desc = 'Semaine d''événement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'Fr', @ref_desc = 'Année Financière de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'Fr', @ref_desc = 'Trimestre Fiscal'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'Fr', @ref_desc = 'Mois Fiscal de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'Fr', @ref_desc = 'Semaine Fiscale de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Julian_Day',              @language = 'Fr', @ref_desc = 'Fr: Julilan Day of Event'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Activity_Event_Id',       @language = 'Fr', @ref_desc = 'Fr: Document Control #'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Measure_Value',           @language = 'Fr', @ref_desc = 'Mesurer la Valeur'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Measure_Type',            @language = 'Fr', @ref_desc = 'Type de Mesure'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Partial_Period',          @language = 'En', @ref_desc = 'Partial Period?'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Partial_Period',          @language = 'Fr', @ref_desc = 'Période Partielle?'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'En', @ref_desc = 'Hierarchy One Name'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'Fr', @ref_desc = 'Hiérarchie un Nom'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Gen_Hover_Data',          @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-TITLE-B%</b>: %AXIS-B%<extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Gen_Hover_Data',          @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-TITLE-B%</b>: %AXIS-B%<extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Bubble_Hover_Data',       @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Bubble_Hover_Data',       @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Bubble_Fixed_Hover_Data',       @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Bubble_Fixed_Hover_Data',       @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'

EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H0', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 1 (Haut)'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H0', @language = 'En', @ref_desc = 'Organization Level 1 (Top)'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H1', @language = 'En', @ref_desc = 'Organization Level 2'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H1', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 2'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H2', @language = 'En', @ref_desc = 'Organization Level 3'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H2', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 3'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H3', @language = 'En', @ref_desc = 'Organization Level 4'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H3', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 4'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H4', @language = 'En', @ref_desc = 'Organization Level 5'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H4', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 5'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H5', @language = 'En', @ref_desc = 'Organization'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_H5', @language = 'Fr', @ref_desc = 'Organisation'

EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_OPG_Data_Set',            @language = 'En', @ref_desc = 'Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Variable_Name',           @language = 'En', @ref_desc = 'Document Type'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'En', @ref_desc = 'Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'En', @ref_desc = 'Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Date_Of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Date_of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'En', @ref_desc = 'Calendar Entry Type'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Year_of_Event',           @language = 'En', @ref_desc = 'Year of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Quarter',                 @language = 'En', @ref_desc = 'Quarter'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Month_of_Event',          @language = 'En', @ref_desc = 'Month of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Week_of_Event',           @language = 'En', @ref_desc = 'Week of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'En', @ref_desc = 'Fiscal Year of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'En', @ref_desc = 'Fiscal Quarter'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'En', @ref_desc = 'Fiscal Month of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'En', @ref_desc = 'Fiscal Week of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Julian_Day',              @language = 'En', @ref_desc = 'Julian Day of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Activity_Event_Id',       @language = 'En', @ref_desc = 'Document Control #'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Measure_Value',           @language = 'En', @ref_desc = 'Measure Value'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Measure_Type',            @language = 'En', @ref_desc = 'Measure Type'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_OPG_Data_Set',            @language = 'Fr', @ref_desc = 'Fr: Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Variable_Name',           @language = 'Fr', @ref_desc = 'Fr: Document Type'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Date_Of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Date_of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'Fr', @ref_desc = 'Type d''entrée d''Agenda'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Year_of_Event',           @language = 'Fr', @ref_desc = 'Année de l''événement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Quarter',                 @language = 'Fr', @ref_desc = 'Trimestre'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Month_of_Event',          @language = 'Fr', @ref_desc = 'Mois de l''événement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Week_of_Event',           @language = 'Fr', @ref_desc = 'Semaine d''événement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'Fr', @ref_desc = 'Année Financière de l''événement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'Fr', @ref_desc = 'Trimestre Fiscal'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'Fr', @ref_desc = 'Mois Fiscal de l''événement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'Fr', @ref_desc = 'Semaine Fiscale de l''événement'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Julian_Day',              @language = 'Fr', @ref_desc = 'Fr: Julilan Day of Event'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Activity_Event_Id',       @language = 'Fr', @ref_desc = 'Fr: Document Control #'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Measure_Value',           @language = 'Fr', @ref_desc = 'Mesurer la Valeur'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Measure_Type',            @language = 'Fr', @ref_desc = 'Type de Mesure'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'En', @ref_desc = 'Hierarchy One Name'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'Fr', @ref_desc = 'Hiérarchie un Nom'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Gen_Hover_Data',          @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-TITLE-B%</b>: %AXIS-B%<extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Gen_Hover_Data',          @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-TITLE-B%</b>: %AXIS-B%<extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Bubble_Hover_Data',       @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Bubble_Hover_Data',       @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'

EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H1', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 1 (Haut)'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H1', @language = 'En', @ref_desc = 'Organization Level 1 (Top)'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H2', @language = 'En', @ref_desc = 'Organization Level 2'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H2', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 2'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H3', @language = 'En', @ref_desc = 'Organization Level 3'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H3', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 3'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H4', @language = 'En', @ref_desc = 'Organization Level 4'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H4', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 4'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H5', @language = 'En', @ref_desc = 'Organization Level 5'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H5', @language = 'Fr', @ref_desc = 'Niveau d''Organisation 5'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H6', @language = 'En', @ref_desc = 'Organization'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_H6', @language = 'Fr', @ref_desc = 'Organisation'

EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_OPG_Data_Set',            @language = 'En', @ref_desc = 'Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Variable_Name',           @language = 'En', @ref_desc = 'Document Type'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'En', @ref_desc = 'Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'En', @ref_desc = 'Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Date_Of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Date_of_Event',           @language = 'En', @ref_desc = 'Date of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'En', @ref_desc = 'Calendar Entry Type'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Year_of_Event',           @language = 'En', @ref_desc = 'Year of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Quarter',                 @language = 'En', @ref_desc = 'Quarter'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Month_of_Event',          @language = 'En', @ref_desc = 'Month of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Week_of_Event',           @language = 'En', @ref_desc = 'Week of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'En', @ref_desc = 'Fiscal Year of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'En', @ref_desc = 'Fiscal Quarter'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'En', @ref_desc = 'Fiscal Month of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'En', @ref_desc = 'Fiscal Week of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Julian_Day',              @language = 'En', @ref_desc = 'Julian Day of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Activity_Event_Id',       @language = 'En', @ref_desc = 'Document Control #'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Measure_Value',           @language = 'En', @ref_desc = 'Measure Value'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Measure_Type',            @language = 'En', @ref_desc = 'Measure Type'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_OPG_Data_Set',            @language = 'Fr', @ref_desc = 'Fr: Data Set Name'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Variable_Name',           @language = 'Fr', @ref_desc = 'Fr: Document Type'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Variable_Name_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Variable_Name_Sub_Qualifier', @language = 'Fr', @ref_desc = 'Fr: Document Type Sub Qualifier'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Date_Of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Date_of_Event',           @language = 'Fr', @ref_desc = 'Date de l''évènement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Calendar_Entry_Type',     @language = 'Fr', @ref_desc = 'Type d''entrée d''Agenda'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Year_of_Event',           @language = 'Fr', @ref_desc = 'Année de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Quarter',                 @language = 'Fr', @ref_desc = 'Trimestre'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Month_of_Event',          @language = 'Fr', @ref_desc = 'Mois de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Week_of_Event',           @language = 'Fr', @ref_desc = 'Semaine d''événement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Year_of_Event',    @language = 'Fr', @ref_desc = 'Année Financière de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Quarter',          @language = 'Fr', @ref_desc = 'Trimestre Fiscal'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Month_of_Event',   @language = 'Fr', @ref_desc = 'Mois Fiscal de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Fiscal_Week_of_Event',    @language = 'Fr', @ref_desc = 'Semaine Fiscale de l''événement'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Julian_Day',              @language = 'Fr', @ref_desc = 'Fr: Julilan Day of Event'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Activity_Event_Id',       @language = 'Fr', @ref_desc = 'Fr: Document Control #'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Measure_Value',           @language = 'Fr', @ref_desc = 'Mesurer la Valeur'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Measure_Type',            @language = 'Fr', @ref_desc = 'Type de Mesure'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'En', @ref_desc = 'Hierarchy One Name'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Hierarchy_One_Name',      @language = 'Fr', @ref_desc = 'Hiérarchie un Nom'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Gen_Hover_Data',          @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-TITLE-B%</b>: %AXIS-B%<extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Gen_Hover_Data',          @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-TITLE-A%</b>: %AXIS-A%<br><b>%AXIS-TITLE-B%</b>: %AXIS-B%<extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Bubble_Hover_Data',       @language = 'En', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Bubble_Hover_Data',       @language = 'Fr', @ref_desc = '<b>%{customdata[0]}</b><br><b>%{customdata[1]}</b><br><b>%AXIS-X-A% -  %AXIS-X-B%</b>: %X-AXIS% <br><b>%AXIS-Y-A% -  %AXIS-Y-B%</b>: %Y-AXIS% <br><b>%AXIS-Z-A% -  %AXIS-Z-B%</b>: %Z-AXIS% <extra></extra>'

EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Link', @language = 'En', @ref_desc = 'Master File'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Link', @language = 'En', @ref_desc = 'Master File'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Link', @language = 'En', @ref_desc = 'Master File'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Link', @language = 'En', @ref_desc = 'Master File'
EXEC InsertOPRef @ref_table = 'OPG001', @ref_value = 'LBL_Link', @language = 'Fr', @ref_desc = 'Fr: Master File'
EXEC InsertOPRef @ref_table = 'OPG010', @ref_value = 'LBL_Link', @language = 'Fr', @ref_desc = 'Fr: Master File'
EXEC InsertOPRef @ref_table = 'OPG011', @ref_value = 'LBL_Link', @language = 'Fr', @ref_desc = 'Fr: Master File'
EXEC InsertOPRef @ref_table = 'OPG001C', @ref_value = 'LBL_Link', @language = 'Fr', @ref_desc = 'Fr: Master File'

EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG001', @language = 'En', @ref_desc = 'OPG 001 Time Series Measures'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG001', @language = 'Fr', @ref_desc = 'OPG 001 Mesures de Séries Chronologiques'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG001C', @language = 'En', @ref_desc = 'OPG 001C Time Series Measures'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG001C', @language = 'Fr', @ref_desc = 'OPG 001C Mesures de Séries Chronologiques'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG010', @language = 'En', @ref_desc = 'OPG010 SanKey Series'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG010', @language = 'Fr', @ref_desc = 'OPG010 Série SanKey'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG011', @language = 'En', @ref_desc = 'OPG 011 Truncated Time Series Measures'
EXEC InsertOPRef @ref_table = 'Data_set', @ref_value = 'OPG011', @language = 'Fr', @ref_desc = 'OPG 011 Mesures de séries chronologiques tronquées'

EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Parameters', @language = 'En', @ref_desc = 'Parameters'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Parameters',@language = 'Fr', @ref_desc = 'Paramètres'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph', @language = 'En', @ref_desc = 'Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph', @language = 'Fr', @ref_desc = 'Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphing_App', @language = 'En', @ref_desc = 'Graphing App'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphing_App', @language = 'Fr', @ref_desc = 'Application Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy', @language = 'En', @ref_desc = 'Hierarchy'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy', @language = 'Fr', @ref_desc = 'Hiérarchie'
Exec InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Level_Filter', @language = 'En', @ref_desc = 'Level Filter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Level_Filter', @language = 'Fr', @ref_desc = 'Filtre de Niveau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Specific_Item', @language = 'En', @ref_desc = 'Specific Item'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Specific_Item', @language = 'Fr', @ref_desc = 'Article Spécifique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select', @language = 'En', @ref_desc = 'Select'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select', @language = 'Fr', @ref_desc = 'Sélectionner'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_Range', @language = 'En', @ref_desc = 'Select Range'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_Range', @language = 'Fr', @ref_desc = 'Sélectionnez la plage'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Timeframe', @language = 'En', @ref_desc = 'TimeFrame'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Timeframe', @language = 'Fr', @ref_desc = 'Plage de Temps'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Year', @language = 'En', @ref_desc = 'Year'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Year', @language = 'Fr', @ref_desc = 'Année'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Year',@language = 'En', @ref_desc = 'Fiscal Year'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal_Year', @language = 'Fr', @ref_desc = 'Exercice fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Month', @language = 'En', @ref_desc = 'Month'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Month', @language = 'Fr', @ref_desc = 'Mois'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Week', @language = 'En', @ref_desc = 'Week'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Week', @language = 'Fr', @ref_desc = 'semaine'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarter', @language = 'En', @ref_desc = 'Quarter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarter', @language = 'Fr', @ref_desc = 'Trimestre'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Type', @language = 'En', @ref_desc = 'Graph Type'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Type', @language = 'Fr', @ref_desc = 'Type de Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis', @language = 'En', @ref_desc = 'X-Axis'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis', @language = 'Fr', @ref_desc = 'Axe X'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis', @language = 'En', @ref_desc = 'Y-Axis'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis', @language = 'Fr', @ref_desc = 'Axe Y'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bubble', @language = 'En', @ref_desc = 'Bubble'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bubble', @language = 'Fr', @ref_desc = 'Bulle'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Line', @language = 'En', @ref_desc = 'Line'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Line', @language = 'Fr', @ref_desc = 'Linéaire'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bar', @language = 'En', @ref_desc = 'Bar'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Bar', @language = 'Fr', @ref_desc = 'Barres'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Scatter', @language = 'En', @ref_desc = 'Scatter'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Scatter', @language = 'Fr', @ref_desc = 'Dispersion'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Partial_Period', @language = 'En', @ref_desc = 'Partial Period'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Partial_Period', @language = 'Fr', @ref_desc = 'Période Partielle'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Options', @language = 'En', @ref_desc = 'Graph Options'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Options', @language = 'Fr', @ref_desc = 'Options de Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Revert', @language = 'En', @ref_desc = 'Revert'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Revert', @language = 'Fr', @ref_desc = 'Revenir'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_To_Top', @language = 'En', @ref_desc = 'To Top'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_To_Top', @language = 'Fr', @ref_desc = 'Au Début'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_In_Dropdown', @language = 'En', @ref_desc = 'Graph All in Dropdown'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_In_Dropdown', @language = 'Fr', @ref_desc = 'Graphique Tout dans la Liste Déroulante'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Time', @language = 'En', @ref_desc = 'Time'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Time',@language = 'Fr', @ref_desc = 'Temps'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Names', @language = 'En', @ref_desc = 'Variable Names'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Variable_Names', @language = 'Fr', @ref_desc = 'Noms de Variables'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children', @language = 'En', @ref_desc = 'Children'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children', @language = 'Fr', @ref_desc = 'Enfants'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_TRUE',@language = 'En', @ref_desc = 'TRUE'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_TRUE',@language = 'Fr', @ref_desc = 'Vrai'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_FALSE',@language = 'En', @ref_desc = 'FALSE'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_FALSE',@language = 'Fr', @ref_desc = 'Faux'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Add_Tile',@language = 'En', @ref_desc = 'Add Tile'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Add_Tile',@language = 'Fr', @ref_desc = 'Fr: Add Tile'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_View',@language = 'En', @ref_desc = 'View'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_View',@language = 'Fr', @ref_desc = 'Vue'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data',@language = 'En', @ref_desc = 'Data'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data',@language = 'Fr', @ref_desc = 'Données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Set',@language = 'En', @ref_desc = 'Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Set',@language = 'Fr', @ref_desc = 'Base de données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Customize',@language = 'En', @ref_desc = 'Customize'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Customize',@language = 'Fr', @ref_desc = 'Personnaliser'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Graph_Title',@language = 'En', @ref_desc = 'Enter Graph Title'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Graph_Title',@language = 'Fr', @ref_desc = 'Entrez le Titre du Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Table',@language = 'En', @ref_desc = 'Table'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Table',@language = 'Fr', @ref_desc = 'Tableau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Toggle_Columns',@language = 'En', @ref_desc = 'Toggle Columns'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Toggle_Columns',@language = 'Fr', @ref_desc = 'Basculer les Colonnes'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Box_Plot',@language = 'En', @ref_desc = 'Box Plot'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Box_Plot',@language = 'Fr', @ref_desc = 'Boîte à Moustaches'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Show_Data_Points',@language = 'En', @ref_desc = 'Show Data Points'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Show_Data_Points',@language = 'Fr', @ref_desc = 'Afficher les Points de Données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Horizontal',@language = 'En', @ref_desc = 'Horizontal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Horizontal',@language = 'Fr', @ref_desc = 'Horizontal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Vertical',@language = 'En', @ref_desc = 'Vertical'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Vertical',@language = 'Fr', @ref_desc = 'Vertical'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphed_Variables',@language = 'En', @ref_desc = 'Graphed Variables'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphed_Variables',@language = 'Fr', @ref_desc = 'Variables Graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Median',@language = 'En', @ref_desc = 'Median'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Median',@language = 'Fr', @ref_desc = 'Médiane'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Min',@language = 'En', @ref_desc = 'Min'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Min',@language = 'Fr', @ref_desc = 'Min'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Max',@language = 'En', @ref_desc = 'Max'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Max',@language = 'Fr', @ref_desc = 'Max'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Distribution',@language = 'En', @ref_desc = 'Distribution'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Distribution',@language = 'Fr', @ref_desc = 'Distribution'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Calendar_Type',@language = 'En', @ref_desc = 'Calendar Type'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Calendar_Type',@language = 'Fr', @ref_desc = 'Type de Calendrier'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Gregorian',@language = 'En', @ref_desc = 'Gregorian'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Gregorian',@language = 'Fr', @ref_desc = 'Grégorien'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal',@language = 'En', @ref_desc = 'Fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Fiscal',@language = 'Fr', @ref_desc = 'Fiscal'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_All_Time_Monthly',@language = 'En', @ref_desc = 'All-Time (Monthly)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_All_Time_Monthly',@language = 'Fr', @ref_desc = 'Tous les temps (mensuel)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Last',@language = 'En', @ref_desc = 'Last'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Last',@language = 'Fr', @ref_desc = 'Dernière'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Years',@language = 'En', @ref_desc = 'Year(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Years',@language = 'Fr', @ref_desc = 'Année(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Months',@language = 'En', @ref_desc = 'Month(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Months',@language = 'Fr', @ref_desc = 'Mois'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarters',@language = 'En', @ref_desc = 'Quarter(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Quarters',@language = 'Fr', @ref_desc = 'Trimestre(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Weeks',@language = 'En', @ref_desc = 'Week(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Weeks',@language = 'Fr', @ref_desc = 'Semaine(s)'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Available',@language = 'En', @ref_desc = 'Available'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Available',@language = 'Fr', @ref_desc = 'Disponible'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Roots_Children',@language = 'En', @ref_desc = 'Root''s Children'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Roots_Children',@language = 'Fr', @ref_desc = 'Les Enfants de Root'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Back',@language = 'En', @ref_desc = 'Back'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Back',@language = 'Fr', @ref_desc = 'Arrière'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Top',@language = 'En', @ref_desc = 'Top'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Top',@language = 'Fr', @ref_desc = 'Haut'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axis_Measure',@language = 'En', @ref_desc = 'Axis Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axis_Measure',@language = 'Fr', @ref_desc = 'Mesure d''Axe'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Orientation',@language = 'En', @ref_desc = 'Graph Orientation'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Orientation',@language = 'Fr', @ref_desc = 'Orientation du Graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Num_Of_Rows',@language = 'En', @ref_desc = '# of rows'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Num_Of_Rows',@language = 'Fr', @ref_desc = '# de Ros'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Filter_The_Table',@language = 'En', @ref_desc = 'How to Filter the Table'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Filter_The_Table',@language = 'Fr', @ref_desc = 'Comment Filtrer le Tableau'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Hide_Columns',@language = 'En', @ref_desc = 'How to Hide Columns'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_How_To_Hide_Columns',@language = 'Fr', @ref_desc = 'Comment Masquer les Colonnes'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date',@language = 'En', @ref_desc = 'Date'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date',@language = 'Fr', @ref_desc = 'Date'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Root',@language = 'En', @ref_desc = 'Root'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Root',@language = 'Fr', @ref_desc = 'l'' Orine'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Group_By',@language = 'En', @ref_desc = 'Group By'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Group_By',@language = 'Fr', @ref_desc = 'Par Groupe'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children_Of',@language = 'En', @ref_desc = 'Children '
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Children_Of',@language = 'Fr', @ref_desc = 'Les Enfants de'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Tab',@language = 'En', @ref_desc = 'Tab'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Tab',@language = 'Fr', @ref_desc = 'Onglet'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs',@language = 'En', @ref_desc = 'Graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs',@language = 'Fr', @ref_desc = 'Graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_The_Graph',@language = 'En', @ref_desc = 'Save The Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_The_Graph',@language = 'Fr', @ref_desc = 'Enregistrer le graphique:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Graph',@language = 'En', @ref_desc = 'Select a saved graph:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Graph',@language = 'Fr', @ref_desc = 'Sélectionnez un graphique enregistré:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Graph',@language = 'En', @ref_desc = 'Delete a saved graph:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Graph',@language = 'Fr', @ref_desc = 'Supprimer un graphique enregistré:'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Graph',@language = 'En', @ref_desc = 'Save Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Graph',@language = 'Fr', @ref_desc = 'Enregistrer le graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Delete',@language = 'En', @ref_desc = 'Confirm Delete'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Delete',@language = 'Fr', @ref_desc = 'Confirmation de la Suppression'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Dashboard_Title',@language = 'En', @ref_desc = 'Enter Dashboard Title'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Enter_Dashboard_Title',@language = 'Fr', @ref_desc = 'Entrez le titre du tableau de bord'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Dashboard',@language = 'En', @ref_desc = 'Save Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save_Dashboard',@language = 'Fr', @ref_desc = 'Enregistrez le tableau de bord'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Dashboard',@language = 'En', @ref_desc = 'Delete a saved dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_A_Saved_Dashboard',@language = 'Fr', @ref_desc = 'Supprimer un tableau de bord enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboards_Require_A_Title_To_Be_Saved',@language = 'En', @ref_desc = 'Dashboards require a title to be saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboards_Require_A_Title_To_Be_Saved',@language = 'Fr', @ref_desc = 'Les tableaux de bord nécessitent un titre pour être enregistrés'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_Siblings',@language = 'En', @ref_desc = 'Graph All Siblings'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_All_Siblings',@language = 'Fr', @ref_desc = 'Graphique de tous les frères et sœurs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Data_Found',@language = 'En', @ref_desc = 'No Data Found'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Data_Found',@language = 'Fr', @ref_desc = 'Base de Données'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs_Require_A_Title_To_Be_Saved',@language = 'En', @ref_desc = 'Graphs require a title to be saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graphs_Require_A_Title_To_Be_Saved',@language = 'Fr', @ref_desc = 'Les graphiques nécessitent un titre pour être enregistrés'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Graph_Has_Been_Saved',@language = 'En', @ref_desc = 'The graph has been saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Graph_Has_Been_Saved',@language = 'Fr', @ref_desc = 'Le graphique a été enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Graph_With_This_Title_Already_Exists',@language = 'En', @ref_desc = 'A saved graph with this title already exists'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Graph_With_This_Title_Already_Exists',@language = 'Fr', @ref_desc = 'Un graphique enregistré avec ce titre existe déjà'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Dashboard_Has_Been_Saved',@language = 'En', @ref_desc = 'The dashboard has been saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_The_Dashboard_Has_Been_Saved',@language = 'Fr', @ref_desc = 'Le tableau de bord a été enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboard_Must_Not_Be_Empty',@language = 'En', @ref_desc = 'Dashboard must not be empty'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Dashboard_Must_Not_Be_Empty',@language = 'Fr', @ref_desc = 'Le tableau de bord ne doit pas être vide'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Dashboard_With_This_Title_Already_Exists',@language = 'En', @ref_desc = 'A saved dashboard with this title already exists'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_A_Saved_Dashboard_With_This_Title_Already_Exists',@language = 'Fr', @ref_desc = 'Un tableau de bord enregistré avec ce titre existe déjà'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Saved_Graphs_Already_Exist_For',@language = 'En', @ref_desc = 'Saved graphs already exist for'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Saved_Graphs_Already_Exist_For',@language = 'Fr', @ref_desc = 'Des graphiques enregistrés existent déjà pour'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Dashboard',@language = 'En', @ref_desc = 'Select a saved dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Select_A_Saved_Dashboard',@language = 'Fr', @ref_desc = 'Sélectionnez un tableau de bord enregistré'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Save_Attempt',@language = 'En', @ref_desc = 'Cancel save attempt'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Save_Attempt',@language = 'Fr', @ref_desc = 'Annuler la tentative de sauvegarde'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard',@language = 'En', @ref_desc = 'Overwrite dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard',@language = 'Fr', @ref_desc = 'Écraser le tableau de bord'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graph',@language = 'En', @ref_desc = 'and the graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graph',@language = 'Fr', @ref_desc = 'et le graphique'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graphs',@language = 'En', @ref_desc = 'and the graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_And_The_Graphs',@language = 'Fr', @ref_desc = 'et les graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graphs',@language = 'En', @ref_desc = 'Overwrite Graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graphs',@language = 'Fr', @ref_desc = 'Écraser les graphiques'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Reset_Attempt',@language = 'En', @ref_desc = 'Cancel reset attempt'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel_Reset_Attempt',@language = 'Fr', @ref_desc = 'Annuler la tentative de réinitialisation'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Sankey',@language = 'En', @ref_desc = 'Sankey'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Sankey',@language = 'Fr', @ref_desc = 'Fr: Saey'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Refresh_Data_Set',@language = 'En', @ref_desc = 'Refresh Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Refresh_Data_Set',@language = 'Fr', @ref_desc = 'Fr: Refresh Data Set'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Data_Set_Load',@language = 'En', @ref_desc = 'Confirm Data Set Load'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confirm_Data_Set_Load',@language = 'Fr', @ref_desc = 'Fr: Confirm Data Set Load'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard_All_Unsaved_Changes_will_Be_Lost',@language = 'En', @ref_desc = 'Reset dashboard all unsaved changes will be lost'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard_All_Unsaved_Changes_will_Be_Lost',@language = 'Fr', @ref_desc = 'Réinitialiser le tableau de bord - toutes les modifications non enregistrées seront perdues'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis_Measure',@language = 'En', @ref_desc = 'X-Axis Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_X_Axis_Measure',@language = 'Fr', @ref_desc = 'Mesure de l axe X'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis_Measure',@language = 'En', @ref_desc = 'Y-Axis Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Y_Axis_Measure',@language = 'Fr', @ref_desc = 'Mesure de l axe Y'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size',@language = 'En', @ref_desc = 'Size'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size',@language = 'Fr', @ref_desc = 'Taille'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size_Measure',@language = 'En', @ref_desc = 'Size Measure'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Size_Measure',@language = 'Fr', @ref_desc = 'Mesure de la taille'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Animate_Over_Time',@language = 'En', @ref_desc = 'Animate Over Time'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Animate_Over_Time',@language = 'Fr', @ref_desc = 'Animer au fil du temps'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Accessed_On',@language = 'En', @ref_desc = 'Data accessed on'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Accessed_On',@language = 'Fr', @ref_desc = 'Données consultées le'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Data_Specified',@language = 'En', @ref_desc = 'No Data Specified'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Data_Specified',@language = 'Fr', @ref_desc = 'Aucune donnée spécifiée'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Make_A_Hierarchy_Selection',@language = 'En', @ref_desc = 'Make a Hierarchy Selection'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Make_A_Hierarchy_Selection',@language = 'Fr', @ref_desc = 'Fr: Make a Hierarchy Selection'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Make_A_Variable_Selection',@language = 'En', @ref_desc = 'Make a Variable Selection'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Make_A_Variable_Selection',@language = 'Fr', @ref_desc = 'Fr: Make a Variable Selection'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Please_Select_A_Data_Set_To_View_Customization_Options',@language = 'En', @ref_desc = 'Please select a data set to view customization options'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Please_Select_A_Data_Set_To_View_Customization_Options',@language = 'Fr', @ref_desc = 'Please select a data set to view customization options'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Lines',@language = 'En', @ref_desc = 'Lines'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Lines',@language = 'Fr', @ref_desc = 'Fr: Lines'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Points',@language = 'En', @ref_desc = 'Points'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Points',@language = 'Fr', @ref_desc = 'Fr: Points'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Lines_And_Points',@language = 'En', @ref_desc = 'Lines and Points'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Lines_And_Points',@language = 'Fr', @ref_desc = 'Fr: Lines and Points'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Display',@language = 'En', @ref_desc = 'Display'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Display',@language = 'Fr', @ref_desc = 'Fr: Display'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Edit',@language = 'En', @ref_desc = 'Edit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Edit',@language = 'Fr', @ref_desc = 'Fr: Edit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save',@language = 'En', @ref_desc = 'Save'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Save',@language = 'Fr', @ref_desc = 'Fr: Save'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load',@language = 'En', @ref_desc = 'Load'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load',@language = 'Fr', @ref_desc = 'Fr: Load'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete',@language = 'En', @ref_desc = 'Delete'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete',@language = 'Fr', @ref_desc = 'Fr: Delete'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Graph',@language = 'En', @ref_desc = 'Untitled Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Graph',@language = 'Fr', @ref_desc = 'Fr: Untitled Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Graph_Prompt',@language = 'En', @ref_desc = 'Graphs require a title to be saved. Please input a title before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: Graphs require a title to be saved. Please input a title before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graph',@language = 'En', @ref_desc = 'Overwrite Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graph',@language = 'Fr', @ref_desc = 'Fr: Overwrite Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graph_Prompt',@language = 'En', @ref_desc = 'A graph with the same title already exists. Do you want to overwrite it?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: A graph with the same title already exists. Do you want to overwrite it?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Graph_Has_Been_Saved',@language = 'En', @ref_desc = '"{}" Has Been Saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Graph_Has_Been_Saved',@language = 'Fr', @ref_desc = 'Fr: "{}" Has Been Saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Graph',@language = 'En', @ref_desc = 'Delete Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Graph',@language = 'Fr', @ref_desc = 'Fr: Delete Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Graph_Prompt',@language = 'En', @ref_desc = 'Delete "{}"?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: Delete "{}"?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Graph_Has_Been_Deleted',@language = 'En', @ref_desc = '"{}" Has Been Deleted'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Graph_Has_Been_Deleted',@language = 'Fr', @ref_desc = 'Fr: "{}" Has Been Deleted'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Graph',@language = 'En', @ref_desc = 'Load Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Graph',@language = 'Fr', @ref_desc = 'Fr: Load Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Graph_Prompt',@language = 'En', @ref_desc = 'WARNING: Your graph has unsaved changes. Continuing your load will overwrite this graph.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: WARNING: Your graph has unsaved changes. Continuing your load will overwrite this graph.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Graph_Has_Been_Loaded',@language = 'En', @ref_desc = '"{}" Has Been Loaded'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Graph_Has_Been_Loaded',@language = 'Fr', @ref_desc = 'Fr: "{}" Has Been Loaded'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Dashboard',@language = 'En', @ref_desc = 'Untitled Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Dashboard',@language = 'Fr', @ref_desc = 'Fr: Untitled Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Dashboard_Prompt',@language = 'En', @ref_desc = 'Dashboards require a title to be saved. Please input a title before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Untitled_Dashboard_Prompt',@language = 'Fr', @ref_desc = 'Fr: Dashboards require a title to be saved. Please input a title before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard',@language = 'En', @ref_desc = 'Overwrite Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard',@language = 'Fr', @ref_desc = 'Fr: Overwrite Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_Prompt',@language = 'En', @ref_desc = 'A Dashboard with the same title already exists. Do you want to overwrite it?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_Prompt',@language = 'Fr', @ref_desc = 'Fr: A Dashboard with the same title already exists. Do you want to overwrite it?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Saved',@language = 'En', @ref_desc = '"{}" Has Been Saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Saved',@language = 'Fr', @ref_desc = 'Fr: "{}" Has Been Saved'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Dashboard',@language = 'En', @ref_desc = 'Delete Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Dashboard',@language = 'Fr', @ref_desc = 'Fr: Delete Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Dashboard_Prompt',@language = 'En', @ref_desc = 'Delete "{}"?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Delete_Dashboard_Prompt',@language = 'Fr', @ref_desc = 'Fr: Delete "{}"?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Deleted',@language = 'En', @ref_desc = '"{}" Has Been Deleted'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Deleted',@language = 'Fr', @ref_desc = 'Fr: "{}" Has Been Deleted'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dashboard',@language = 'En', @ref_desc = 'Load Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dashboard',@language = 'Fr', @ref_desc = 'Fr: Load Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dashboard_Prompt',@language = 'En', @ref_desc = 'WARNING: Your Dashboard has unsaved changes. Continuing your load will overwrite this Dashboard.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dashboard_Prompt',@language = 'Fr', @ref_desc = 'Fr: WARNING: Your Dashboard has unsaved changes. Continuing your load will overwrite this Dashboard.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Loaded',@language = 'En', @ref_desc = '"{}" Has Been Loaded'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Loaded',@language = 'Fr', @ref_desc = 'Fr: "{}" Has Been Loaded'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard',@language = 'En', @ref_desc = 'Reset Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard',@language = 'Fr', @ref_desc = 'Fr: Reset Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard_Prompt',@language = 'En', @ref_desc = 'Resetting this dashboard will clear all your selections on the dashboard and reset them to defaults. Continue?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset_Dashboard_Prompt',@language = 'Fr', @ref_desc = 'Fr: Resetting this dashboard will clear all your selections on the dashboard and reset them to defaults. Continue?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Reset',@language = 'En', @ref_desc = 'Dashboard Has Been Reset'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Your_Dashboard_Has_Been_Reset',@language = 'Fr', @ref_desc = 'Fr: Dashboard Has Been Reset'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Dashboard',@language = 'En', @ref_desc = 'Empty Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Dashboard',@language = 'Fr', @ref_desc = 'Fr: Empty Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Dashboard_Prompt',@language = 'En', @ref_desc = 'Dashboards require graphs to be saved. Please add some graphs before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Dashboard_Prompt',@language = 'Fr', @ref_desc = 'Fr: Dashboards require graphs to be saved. Please add some graphs before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_C_Title_Graph_Prompt',@language = 'En', @ref_desc = 'A Dashboard with the same title ["{}"] already exists and the graphs {} already exist. Do you want to overwrite them?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_C_Title_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: A Dashboard with the same title ["{}"] already exists and the graphs {} already exist. Do you want to overwrite them?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_C_Graph_Prompt',@language = 'En', @ref_desc = 'The graphs {} already exist. Do you want to overwrite them?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_C_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: The graphs {} already exist. Do you want to overwrite them?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_C_Title_Prompt',@language = 'En', @ref_desc = 'A Dashboard with the same title ["{}"] already exists. Do you want to overwrite it?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Overwrite_Dashboard_C_Title_Prompt',@language = 'Fr', @ref_desc = 'Fr: A Dashboard with the same title ["{}"] already exists. Do you want to overwrite it?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset', @language = 'En', @ref_desc = 'Reset'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Reset', @language = 'Fr', @ref_desc = 'Fr: Reset'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_A_Saved_Dashboard', @language = 'En', @ref_desc = 'Load A Saved Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_A_Saved_Dashboard', @language = 'Fr', @ref_desc = 'Fr: Load A Saved Dashboard'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_A_Saved_Graph', @language = 'En', @ref_desc = 'Load A Saved Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_A_Saved_Graph', @language = 'Fr', @ref_desc = 'Fr: Load A Saved Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Set_Info',@language = 'En', @ref_desc = 'Data set info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Set_Info',@language = 'Fr', @ref_desc = 'Fr: Data set info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_Info',@language = 'En', @ref_desc = 'Hierarchy info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_Info',@language = 'Fr', @ref_desc = 'Fr: Hierarchy info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date_Picker_Info',@language = 'En', @ref_desc = 'Date picker info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Date_Picker_Info',@language = 'Fr', @ref_desc = 'Fr: Date picker info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Options_Info',@language = 'En', @ref_desc = 'Graph options info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Options_Info',@language = 'Fr', @ref_desc = 'Fr: Graph options info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Type_Info',@language = 'En', @ref_desc = 'Graph type info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Graph_Type_Info',@language = 'Fr', @ref_desc = 'Fr: Graph type info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Fitting',@language = 'En', @ref_desc = 'Data fitting'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Fitting',@language = 'Fr', @ref_desc = 'Fr: Data fitting'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Linear_Fit',@language = 'En', @ref_desc = 'Linear fit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Linear_Fit',@language = 'Fr', @ref_desc = 'Fr: Linear fit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Curve_Fit',@language = 'En', @ref_desc = 'Curve fit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Curve_Fit',@language = 'Fr', @ref_desc = 'Fr: Curve fit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Fit',@language = 'En', @ref_desc = 'No fit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_No_Fit',@language = 'Fr', @ref_desc = 'Fr: No fit'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Fitting_Hidden_Info',@language = 'En', @ref_desc = 'Select a specific item from the hierarchy menu to access data fitting.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Fitting_Hidden_Info',@language = 'Fr', @ref_desc = 'Fr: Data fitting info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Fitting_Shown_Info',@language = 'En', @ref_desc = 'When selecting the curve fit option use the input box to adjust the degree of the polynomial.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Data_Fitting_Shown_Info',@language = 'Fr', @ref_desc = 'Fr: Data fitting info'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Show_Grid_Lines',@language = 'En', @ref_desc = 'Show Grid Lines'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Show_Grid_Lines',@language = 'Fr', @ref_desc = 'Fr: Show Grid Lines'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Edit_Graph',@language = 'En', @ref_desc = 'Edit Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Edit_Graph',@language = 'Fr', @ref_desc = 'Fr: Edit Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hide_Legend',@language = 'En', @ref_desc = 'Hide Legend'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hide_Legend',@language = 'Fr', @ref_desc = 'Fr: Hide Legend'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Link_Graph',@language = 'En', @ref_desc = 'Link Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Link_Graph',@language = 'Fr', @ref_desc = 'Fr: Link Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Link_Graph_Prompt',@language = 'En', @ref_desc = 'You are linking this graph to another dataset. Doing so may have unintended results if the linked dataset does not support the used graph type. Continue?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Link_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: You are linking this graph to another dataset. Doing so may have unintended results if the linked dataset does not support the used graph type. Continue?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confidence_Interval',@language = 'En', @ref_desc = 'Fit Confidence Interval'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Confidence_Interval',@language = 'Fr', @ref_desc = 'Fr: Fit Confidence Interval'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Close_Graph',@language = 'En', @ref_desc = 'Close Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Close_Graph',@language = 'Fr', @ref_desc = 'Fr: Close Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Close_Graph_Prompt',@language = 'En', @ref_desc = 'Your graph has unsaved changes. Continue to close this graph?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Close_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: Your graph has unsaved changes. Continue to close this graph?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel',@language = 'En', @ref_desc = 'Cancel'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Cancel',@language = 'Fr', @ref_desc = 'Fr: Cancel'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_OK',@language = 'En', @ref_desc = 'OK'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_OK',@language = 'Fr', @ref_desc = 'Fr: OK'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dataset', @language = 'En', @ref_desc = 'Load Dataset'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dataset', @language = 'Fr', @ref_desc = 'Fr: Load Dataset'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dataset_Prompt', @language = 'En', @ref_desc = 'One or more graphs will be affected by loading this dataset. Please select an option with what to do with these graphs.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dataset_Prompt', @language = 'Fr', @ref_desc = 'Fr: One or more graphs will be affected by loading this dataset. Please select an option with what to do with these graphs.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dataset_Duo_Prompt', @language = 'En', @ref_desc = 'Loading this dataset will modify your graph (progress may be lost). Continue?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Load_Dataset_Duo_Prompt', @language = 'Fr', @ref_desc = 'Fr: Loading this dataset will modify your graph (progress may be lost). Continue?'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Continue_And_Modify_My_Graphs_As_Necessary', @language = 'En', @ref_desc = 'Continue and modify my graphs as necessary'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Continue_And_Modify_My_Graphs_As_Necessary', @language = 'Fr', @ref_desc = 'Fr: Continue and modify my graphs as necessary'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Continue_And_Unlink_My_Graphs', @language = 'En', @ref_desc = 'Continue and unlink my graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Continue_And_Unlink_My_Graphs', @language = 'Fr', @ref_desc = 'Fr: Continue and unlink my graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Graph',@language = 'En', @ref_desc = 'Empty Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Graph',@language = 'Fr', @ref_desc = 'Fr: Empty Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Graph_Prompt',@language = 'En', @ref_desc = 'Your graph is empty. Please select a dataset to load and construct a graph before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Empty_Graph_Prompt',@language = 'Fr', @ref_desc = 'Fr: Your graph is empty. Please select a dataset to load and construct a graph before saving.'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axes_Graph_Labels_Modified', @language = 'En', @ref_desc = 'Your Axes Labels May Not Reflect The Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axes_Graph_Labels_Modified', @language = 'Fr', @ref_desc = 'Fr: Your Axes Labels May Not Reflect The Graph'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axes_Graphs_Labels_Modified', @language = 'En', @ref_desc = 'Your Axes Labels May Not Reflect The Graphs'
EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Axes_Graphs_Labels_Modified', @language = 'Fr', @ref_desc = 'Fr: Your Axes Labels May Not Reflect The Graphs'

--EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_Selection''s_Children',@language = 'En',@ref_desc = 'Hierarchy Selection''s Children'
--EXEC InsertOPRef @ref_table = 'Labels', @ref_value = 'LBL_Hierarchy_Selection''s_Children',@language = 'Fr',@ref_desc = 'Enfants de la Sélection de Hiérarchie'


GO

DROP PROC InsertOPRef
GO
---when we update it from a space to underscore it gives key errors
/*
UPDATE [dbo].[OP_Ref]
SET    ref_value = REPLACE(ref_value, ' ', '_')
WHERE  ref_value LIKE '%[ ]%'
go*/

IF OBJECT_ID('dbo.reftable') IS NOT NULL
    PRINT   'REFTABLE Procedure Exists'

ELSE
	BEGIN
		EXEC('
    Create Proc dbo.reftable

    as
	BEGIN
    Select * From [dbo].[OP_Ref]
		END')
	END
    GO
