USE [OGMA_Test]
GO

/****** Object:  Table [dbo].[OP_ref_insert]    Script Date: 2021-05-19 12:03:31 PM ******/

INSERT into [dbo].[OP_Ref] (ref_table,ref_value, language, ref_desc)
values ('Data_set','OPG001.sql','En','OPG 001 Time Series Measures'),
('Data_set','OPG001.sql','Fr','OPG 001 Mesures de Séries Chronologiques'),
('Data_set','OPG010.sql','En','OPG010 SanKey Series'),
('Data_set','OPG010.sql','Fr','Série SanKey'),
('Labels','LBL_Parameters','En','Parameters'),
('Labels','LBL_Parameters','Fr','Paramètres'),
('Labels','LBL_Graph','En','Graph'),
('Labels','LBL_Graph','Fr','Graphique'),
('Labels','LBL_Graphing_App','En','Graphing App'),
('Labels','LBL_Graphing_App','Fr','Application Graphique'),
('Labels','LBL_Hierarchy','En','Hierarchy'),
('Labels','LBL_Hierarchy','Fr','Hiérarchie'),
('Labels','LBL_Level_Filter','En','Level Filter'),
('Labels','LBL_Level_Filter','Fr','Filtre de Niveau'),
('Labels','LBL_Specific_Item','En','Specific Item'),
('Labels','LBL_Specific_Item','Fr','Article Spécifique'),
('Labels','LBL_Select','En','Select'),
('Labels','LBL_Select','Fr','Sélectionner'),
('Labels','LBL_Timeframe','En','TimeFrame'),
('Labels','LBL_Timeframe','Fr','Plage de Temps'),
('Labels','LBL_Year','En','Year'),
('Labels','LBL_Year','Fr','Année'),
('Labels','LBL_Fiscal_Year','En','Fiscal Year'),
('Labels','LBL_Fiscal_Year','Fr','Exercice fiscal'),
('Labels','LBL_Month','En','Month'),
('Labels','LBL_Month','Fr','Mois'),
('Labels','LBL_Quarter','En','Quarter'),
('Labels','LBL_Quarter','Fr','Trimestre'),
('Labels','LBL_Graph_Type','En','Graph Type'),
('Labels','LBL_Graph_Type','Fr','Type de Graphique'),
('Labels','LBL_X_Axis','En','X-Axis'),
('Labels','LBL_X_Axis','Fr','Axe X'),
('Labels','LBL_Y_Axis','En','Y-Axis'),
('Labels','LBL_Y_Axis','Fr','Axe Y'),
('Labels','LBL_Line','En','Line'),
('Labels','LBL_Line','Fr','Linéaire'),
('Labels','LBL_Bar','En','Bar'),
('Labels','LBL_Bar','Fr','Barres'),
('Labels','LBL_Scatter','En','Scatter'),
('Labels','LBL_Scatter','Fr','Dispersion'),
('Labels','LBL_Partial_Period','En','Partial Period'),
('Labels','LBL_Partial_Period','Fr','Période Partielle'),
('Labels','LBL_Graph_Options','En','Graph Options'),
('Labels','LBL_Graph_Options','Fr','Options de Graphique'),
('Labels','LBL_Revert','En','Revert'),
('Labels','LBL_Revert','Fr','Revenir'),
('Labels','LBL_To_Top','En','To Top'),
('Labels','LBL_To_Top','Fr','Au Début'),
('Labels','LBL_Graph_All_In_Dropdown','En','Graph All in Dropdown'),
('Labels','LBL_Graph_All_In_Dropdown','Fr','Graphique Tout dans la Liste Déroulante'),
('Labels','LBL_Time','En','Time'),
('Labels','LBL_Time','Fr','Temps'),
('Labels','LBL_Variable_Names','En','Variable Names'),
('Labels','LBL_Variable_Names','Fr','Noms de Variables'),
('Labels','LBL_Children','En','Children'),
('Labels','LBL_Children','Fr','Enfants'),
('Labels','LBL_H1','Fr','Niveau d''Organisation 1 (Haut)'),
('Labels','LBL_H1','En','Organization Level 1 (Top)'),
('Labels','LBL_H2','En','Organization Level 2'),
('Labels','LBL_H2','Fr','Niveau d''Organisation 2'),
('Labels','LBL_H3','En','Organization Level 3'),
('Labels','LBL_H3','Fr','Niveau d''Organisation 3'),
('Labels','LBL_H4','En','Organization Level 4'),
('Labels','LBL_H4','Fr','Niveau d''Organisation 4'),
('Labels','LBL_H5','En','Organization Level 5'),
('Labels','LBL_H5','Fr','Niveau d''Organisation 5'),
('Labels','LBL_H6','En','Organization'),
('Labels','LBL_H6','Fr','Organisation'),
('Labels','LBL_TRUE','En','TRUE'),
('Labels','LBL_TRUE','Fr','Vrai'),
('Labels','LBL_FALSE','En','FALSE'),
('Labels','LBL_FALSE','Fr','Faux'),
('Labels','LBL_New','En','New'),
('Labels','LBL_New','Fr','Nouveau'),
('Labels','LBL_View','En','View'),
('Labels','LBL_View','Fr','Vue'),
('Labels','LBL_Data','En','Data'),
('Labels','LBL_Data','Fr','Données'),
('Labels','LBL_Customize','En','Customize'),
('Labels','LBL_Customize','Fr','Personnaliser'),
('Labels','LBL_Enter_Graph_Title','En','Enter Graph Title'),
('Labels','LBL_Enter_Graph_Title','Fr','Entrez le Titre du Graphique'),
('Labels','LBL_Hierarchy_Selection''s_Children','En','Hierarchy Selection''s Children'),
('Labels','LBL_Hierarchy_Selection''s_Children','Fr','Enfants de la Sélection de Hiérarchie'),
('Labels','LBL_Table','En','Table'),
('Labels','LBL_Table','Fr','Tableau'),
('Labels','LBL_Hierarchy_One_Name','En','Hierarchy One Name'),
('Labels','LBL_Hierarchy_One_Name','Fr','Hiérarchie un Nom'),
('Labels','LBL_Variable_Name','En','Document Type'),
('Labels','LBL_Variable_Name','Fr','Nom de Variable'),
('Labels','LBL_Variable_Name_Qualifier','En','Document Type Qualifier'),
('Labels','LBL_Variable_Name_Qualifier','Fr','Qualificateur de Nom de Variable'),
('Labels','LBL_Variable_Name_Sub_Qualifier','En','Document Type Sub Qualifier'),
('Labels','LBL_Variable_Name_Sub_Qualifier','Fr','Sous-Qualificateur de Nom de Variable'),
('Labels','LBL_Date_Of_Event','En','Date of Event'),
('Labels','LBL_Date_Of_Event','Fr','Date de l''évènement'),
('Labels','LBL_Calendar_Entry_Type','En','Calendar Entry Type'),
('Labels','LBL_Calendar_Entry_Type','Fr','Type d''entrée d''Agenda'),
('Labels','LBL_Year_Of_Event','En','Year of Event'),
('Labels','LBL_Year_Of_Event','Fr','Année de l''événement'),
('Labels','LBL_Month_Of_Event','En','Month of Event'),
('Labels','LBL_Month_Of_Event','Fr','Mois de l''événement'),
('Labels','LBL_Week_Of_Event','En','Week of Event'),
('Labels','LBL_Week_Of_Event','Fr','Semaine d''événement'),
('Labels','LBL_Fiscal_Year_Of_Event','En','Fiscal Year of Event'),
('Labels','LBL_Fiscal_Year_Of_Event','Fr','Année Financière de l''événement'),
('Labels','LBL_Fiscal_Quarter','En','Fiscal Quarter'),
('Labels','LBL_Fiscal_Quarter','Fr','Trimestre Fiscal'),
('Labels','LBL_Fiscal_Month_Of_Event','En','Fiscal Month of Event'),
('Labels','LBL_Fiscal_Month_Of_Event','Fr','Mois Fiscal de l''événement'),
('Labels','LBL_Fiscal_Week_Of_Event','En','Fiscal Week of Event'),
('Labels','LBL_Fiscal_Week_Of_Event','Fr','Semaine Fiscale de l''événement'),
('Labels','LBL_Julian_Day','En','Julian Day'),
('Labels','LBL_Julian_Day','Fr','Julian Day'),
('Labels','LBL_Activity_Event_Id','En','Activity Event Id'),
('Labels','LBL_Activity_Event_Id','Fr','ID d''événement d''Activité'),
('Labels','LBL_Measure_Value','En','Measure Value'),
('Labels','LBL_Measure_Value','Fr','Mesurer la Valeur'),
('Labels','LBL_Measure_Type','En','Measure Type'),
('Labels','LBL_Measure_Type','Fr','Type de Mesure'),
('Labels','LBL_Toggle_Columns','En','Toggle Columns'),
('Labels','LBL_Toggle_Columns','Fr','Basculer les Colonnes'),
('Labels','LBL_Box_Plot','En','Box Plot'),
('Labels','LBL_Box_Plot','Fr','Boîte à Moustaches'),
('Labels','LBL_Show_Data_Points','En','Show Data Points'),
('Labels','LBL_Show_Data_Points','Fr','Afficher les Points de Données'),
('Labels','LBL_Horizontal','En','Horizontal'),
('Labels','LBL_Horizontal','Fr','Horizontal'),
('Labels','LBL_Vertical','En','Vertical'),
('Labels','LBL_Vertical','Fr','Vertical'),
('Labels','LBL_Graphed_Variables','En','Graphed Variables'),
('Labels','LBL_Graphed_Variables','Fr','Variables Graphiques'),
('Labels','LBL_Median','En','Median'),
('Labels','LBL_Median','Fr','Médiane'),
('Labels','LBL_Min','En','Min'),
('Labels','LBL_Min','Fr','Min'),
('Labels','LBL_Max','En','Max'),
('Labels','LBL_Max','Fr','Max'),
('Labels','LBL_Distribution','En','Distribution'),
('Labels','LBL_Distribution','Fr','Distribution'),
('Labels','LBL_Calendar_Type','En','Calendar Type'),
('Labels','LBL_Calendar_Type','Fr','Type de Calendrier'),
('Labels','LBL_Gregorian','En','Gregorian'),
('Labels','LBL_Gregorian','Fr','Grégorien'),
('Labels','LBL_Fiscal','En','Fiscal'),
('Labels','LBL_Fiscal','Fr','Fiscal'),
('Labels','LBL_All_Time_Monthly','En','All-Time (Monthly)'),
('Labels','LBL_All_Time_Monthly','Fr','Tous les Temps (Mensuel)'),
('Labels','LBL_Last','En','Last'),
('Labels','LBL_Last','Fr','Dernière'),
('Labels','LBL_Select_Range','En','Select Range'),
('Labels','LBL_Select_Range','Fr','Sélectionnez la Gamme'),
('Labels','LBL_Years','En','Year(s)'),
('Labels','LBL_Years','Fr','Année(s)'),
('Labels','LBL_Months','En','Month(s)'),
('Labels','LBL_Months','Fr','Mois'),
('Labels','LBL_Quarters','En','Quarter(s)'),
('Labels','LBL_Quarters','Fr','Trimestre(s)'),
('Labels','LBL_Weeks','En','Week(s)'),
('Labels','LBL_Weeks','Fr','Semaine(s)'),
('Labels','LBL_Available','En','Available'),
('Labels','LBL_Available','Fr','Valide'),
('Labels','LBL_Week','En','Week'),
('Labels','LBL_Week','Fr','Semaine'),
('Labels','LBL_Root''s_Children','En','Root''s Children'),
('Labels','LBL_Root''s_Children','Fr','Les Enfants de Root'),
('Labels','LBL_Back','En','Back'),
('Labels','LBL_Back','Fr','Arrière'),
('Labels','LBL_Top','En','Top'),
('Labels','LBL_Top','Fr','Haut'),
('Labels','LBL_Axis_Measure','En','Axis Measure'),
('Labels','LBL_Axis_Measure','Fr','Mesure d''Axe'),
('Labels','LBL_Graph_Orientation','En','Graph Orientation'),
('Labels','LBL_Graph_Orientation','Fr','Orientation du Graphique'),
('Labels','LBL_Num_Of_Rows','En','# of Rows'),
('Labels','LBL_Num_Of_Rows','Fr','# de Ros'),
('Labels','LBL_How_To_Filter_The_Table','En','How to Filter the Table'),
('Labels','LBL_How_To_Filter_The_Table','Fr','Comment Filtrer le Tableau'),
('Labels','LBL_How_To_Hide_Columns','En','How to Hide Columns'),
('Labels','LBL_How_To_Hide_Columns','Fr','Comment Masquer les Colonnes'),
('Labels','LBL_Date','En','Date'),
('Labels','LBL_Date','Fr','Date'),
('Labels','LBL_Root','En','Root'),
('Labels','LBL_Root','Fr','l'' Origine'),
('Labels','LBL_Group_By','En','Group By'),
('Labels','LBL_Group_By','Fr','Par Groupe'),
('Labels','LBL_Children_Of','En','Children of'),
('Labels','LBL_Children_Of','Fr','Les Enfants de'),
('Labels','LBL_Tab','En','Tab'),
('Labels','LBL_Tab','Fr','Onglet'),
('Labels','LBL_Graphs','En','Graphs'),
('Labels','LBL_Graphs','Fr','Graphiques'),
('Labels','LBL_Save_The_Graph','En','Save the graph:'),
('Labels','LBL_Save_The_Graph','Fr','Enregistrer le graphique:'),
('Labels','LBL_Select_A_saved_Graph','En','Select a saved graph:'),
('Labels','LBL_Select_A_saved_Graph','Fr','Sélectionnez un graphique enregistré:'),
('Labels','LBL_Delete_A_saved_Graph','En','Delete a saved graph:'),
('Labels','LBL_Delete_A_saved_Graph','Fr','Supprimer un graphique enregistré:'),
('Labels','LBL_Save_Graph','En','Save Graph'),
('Labels','LBL_Save_Graph','Fr','Enregistrer le graphique'),
('Labels','LBL_Confirm_Delete','En','Confirm Delete'),
('Labels','LBL_Confirm_Delete','Fr','Confirmation de la Suppression'),
('Labels','LBL_Enter_Dashboard_Title','En','Enter Dashboard Title'),
('Labels','LBL_Enter_Dashboard_Title','Fr','Entrez le titre du tableau de bord'),
('Labels','LBL_Save_Dashboard','En','Save Dashboard'),
('Labels','LBL_Save_Dashboard','Fr','Enregistrez le tableau de bord'),
('Labels','LBL_Delete_A_Saved_Dashboard','En','Delete a saved dashboard'),
('Labels','LBL_Delete_A_Saved_Dashboard','Fr','Supprimer un tableau de bord enregistré'),
('Labels','LBL_Dashboards_Require_A_Title_To_Be_Saved','En','Dashboards require a title to be saved'),
('Labels','LBL_Dashboards_Require_A_Title_To_Be_Saved','Fr','Les tableaux de bord nécessitent un titre pour être enregistrés'),
('Labels','LBL_Graph_All_Siblings','En','Graph All Siblings'),
('Labels','LBL_Graph_All_Siblings','Fr','Graphique de Tous les fratries'),
('Labels','LBL_No_Data_Found','En','No Data Found'),
('Labels','LBL_No_Data_Found','Fr','Aucune Donnée Disponible'),
('Labels','LBL_No_Data_Specified','En','No Data Specified'),
('Labels','LBL_No_Data_Specified','Fr','Aucune Donnée Spécifiée'),
('Labels','LBL_Data_Accessed_On','En','Data Accessed on'),
('Labels','LBL_Data_Accessed_On','Fr','Données Consultées le '),
('Labels','LBL_Data_Set','En','Data Set'),
('Labels','LBL_Data_Set','Fr','Base de Données'),
('Labels','LBL_Graphs_Require_A_Title_To_Be_Saved','En','Graphs require a title to be saved'),
('Labels','LBL_Graphs_Require_A_Title_To_Be_Saved','Fr','Les graphiques nécessitent un titre pour être enregistrés'),
('Labels','LBL_The_Graph_Has_Been_Saved','En','The graph has been saved'),
('Labels','LBL_The_Graph_Has_Been_Saved','Fr','Le graphique a été enregistré'),
('Labels','LBL_A_Saved_Graph_With_This_Title_Already_Exists','En','A saved graph with this title already exists'),
('Labels','LBL_A_Saved_Graph_With_This_Title_Already_Exists','Fr','Un graphique enregistré avec ce titre existe déjà'),
('Labels','LBL_The_Dashboard_Has_Been_Saved','En','The dashboard has been saved'),
('Labels','LBL_The_Dashboard_Has_Been_Saved','Fr','Le tableau de bord a été enregistré'),
('Labels','LBL_Dashboard_Must_Not_Be_Empty','En','Dashboard must not be empty'),
('Labels','LBL_Dashboard_Must_Not_Be_Empty','Fr','Le tableau de bord ne doit pas être vide'),
('Labels','LBL_A_Saved_Dashboard_With_This_Title_Already_Exists','En','A saved dashboard with this title already exists'),
('Labels','LBL_A_Saved_Dashboard_With_This_Title_Already_Exists','Fr','Un tableau de bord enregistré avec ce titre existe déjà'),
('Labels','LBL_Saved_Graphs_Already_Exist_For','En','Saved graphs already exist for'),
('Labels','LBL_Saved_Graphs_Already_Exist_For','Fr','Des graphiques enregistrés existent déjà pour'),
('Labels','LBL_Select_A_Saved_Dashboard','En','Select a saved dashboard'),
('Labels','LBL_Select_A_Saved_Dashboard','Fr','Sélectionnez un tableau de bord enregistré'),
('Labels','LBL_Cancel_Save_Attempt','En','Cancel save attempt'),
('Labels','LBL_Cancel_Save_Attempt','Fr','Annuler la tentative de sauvegarde'),
('Labels','LBL_Overwrite_Dashboard','En','Overwrite dashboard'),
('Labels','LBL_Overwrite_Dashboard','Fr','Écraser le tableau de bord'),
('Labels','LBL_And_The_Graph','En','and the graph'),
('Labels','LBL_And_The_Graph','Fr','et le graphique'),
('Labels','LBL_And_The_Graphs','En','and the graphs'),
('Labels','LBL_And_The_Graphs','Fr','et les graphiques'),
('Labels','LBL_Overwrite_Graph','En','Overwrite graph'),
('Labels','LBL_Overwrite_Graph','Fr','Écraser le graphique'),
('Labels','LBL_Overwrite_Graphs','En','Overwrite graphs'),
('Labels','LBL_Overwrite_Graphs','Fr','Écraser les graphiques'),
('Labels','LBL_Reset_dashboard_All_Unsaved_Changes_Will_Be_Lost','En','Reset dashboard - all unsaved changes will be lost'),
('Labels','LBL_Reset_dashboard_All_Unsaved_Changes_Will_Be_Lost','Fr','Réinitialiser le tableau de bord - toutes les modifications non enregistrées seront perdues'),
('Labels','LBL_Cancel_Reset_Attempt','En','Cancel reset attempt'),
('Labels','LBL_Cancel_Reset_Attempt','Fr','Annuler la tentative de réinitialisation'),
('Labels','LBL_Sankey','En','Sankey'),
('Labels','LBL_Sankey','Fr','Fr: Sankey'),
('Labels','LBL_In6','En','150+'),
('Labels','LBL_In5','En','121-150'),
('Labels','LBL_In4','En','91-120'),
('Labels','LBL_In3','En','61-90'),
('Labels','LBL_In2','En','31-60'),
('Labels','LBL_In1','En','LT 31'),
('Labels','LBL_End6','En','Cpltd 150+'),
('Labels','LBL_End5','En','Cpltd 121-150'),
('Labels','LBL_End4','En','Cpltd 91-120'),
('Labels','LBL_End3','En','Cpltd 61-90'),
('Labels','LBL_End2','En','Cpltd 31-60'),
('Labels','LBL_End1','En','Cpltd LT 31'),
('Labels','LBL_Out6','En','Cont 150+'),
('Labels','LBL_Out5','En','Cont 121-150'),
('Labels','LBL_Out4','En','Cont 91-120'),
('Labels','LBL_Out3','En','Cont 61-90'),
('Labels','LBL_Out2','En','Cont 31-60'),
('Labels','LBL_Out1','En','Cont LT 31'),
('Labels','LBL_In6_Long','En','Outstanding > 150 days'),
('Labels','LBL_In6_Long','Fr','Fr: Outstanding > 150 days'),
('Labels','LBL_In5_Long','En','Outstanding 121 - 150 days'),
('Labels','LBL_In5_Long','Fr','Fr: Outstanding 121 - 150 days'),
('Labels','LBL_In4_Long','En','Outstanding 91 - 120 days'),
('Labels','LBL_In4_Long','Fr','Fr: Outstanding 91 - 120 days'),
('Labels','LBL_In3_Long','En','Outstanding 61 - 90 days'),
('Labels','LBL_In3_Long','Fr','Fr: Outstanding 61 - 90 days'),
('Labels','LBL_In2_Long','En','Outstanding 31 - 60 days'),
('Labels','LBL_In2_Long','Fr','Fr: Outstanding 31 - 60 days'),
('Labels','LBL_In1_Long','En','Outstanding < 31 days'),
('Labels','LBL_In1_Long','Fr','Fr: Outstanding < 31 days'),
('Labels','LBL_End6_Long','En','Completed > 150 days'),
('Labels','LBL_End6_Long','Fr','Fr: Completed > 150 days'),
('Labels','LBL_End5_Long','En','Completed 121 - 150 days'),
('Labels','LBL_End5_Long','Fr','Fr: Completed 121 - 150 days'),
('Labels','LBL_End4_Long','Fr','Fr: Completed 91 - 120 days'),
('Labels','LBL_End3_Long','En','Completed 61 - 90 days'),
('Labels','LBL_End3_Long','Fr','Fr: Completed 61 - 90 days'),
('Labels','LBL_End2_Long','En','Completed 31 - 60 days'),
('Labels','LBL_End2_Long','Fr','Fr: Completed 31 - 60 days'),
('Labels','LBL_End1_Long','En','Completed < 31 days'),
('Labels','LBL_End1_Long','Fr','Fr: Completed < 31 days'),
('Labels','LBL_New_Long','En','New in last 30 days'),
('Labels','LBL_New_Long','Fr','Fr: New in last 30 days'),
('Labels','LBL_Out6_Long','En','Continued In-Process > 150 days'),
('Labels','LBL_Out6_Long','Fr','Fr: Continued In-Process > 150 days'),
('Labels','LBL_Out5_Long','En','Continued In-Process 121 - 150 days'),
('Labels','LBL_Out5_Long','Fr','Fr: Continued In-Process 121 - 150 days'),
('Labels','LBL_Out4_Long','En','Continued In-Process 91 - 120 days'),
('Labels','LBL_Out4_Long','Fr','Fr: Continued In-Process 91 - 120 days'),
('Labels','LBL_Out3_Long','En','Continued In-Process 61 - 90 days'),
('Labels','LBL_Out3_Long','Fr','Fr: Continued In-Process 61 - 90 days'),
('Labels','LBL_Out2_Long','En','Continued In-Process 31 - 60 days'),
('Labels','LBL_Out2_Long','Fr','Fr: Continued In-Process 31 - 60 days'),
('Labels','LBL_Out1_Long','En','Continued In-Process < 31 days'),
('Labels','LBL_Out1_Long','Fr','Fr: Continued In-Process < 31 days'),
('Labels','LBL_End','En','Cpltd'),
('Labels','LBL_End','Fr','Fr: Cpltd'),
('Labels','LBL_End_Long','En','Completed'),
('Labels','LBL_End_Long','Fr','Fr: Completed');


go
---when we update it from a space to underscore it gives key errors
/*
UPDATE [dbo].[OP_Ref]
SET    ref_value = REPLACE(ref_value, ' ', '_')
WHERE  ref_value LIKE '%[ ]%'
go*/

IF OBJECT_ID('dbo.reftable') IS NOT NULL
    PRINT   'REFTABLE Procedure Exists'

ELSE
	BEGIN
		EXEC('
    Create Proc dbo.reftable

    as
	BEGIN
    Select * From [dbo].[OP_Ref]
		END')
	END
    go

/*
exec dbo.reftable
go*/