USE [OGMA_Test]
GO

/****** Object:  Table [dbo].[OP_ref_insert]    Script Date: 2021-05-19 12:03:31 PM ******/

INSERT into [dbo].[OP_Ref] (ref_table,ref_value, language, ref_desc)
values ('Data_set','OPG001.sql','En','OPG 001 Time Series Measures'),
('Data_set','OPG001.sql','Fr','OPG 001 Mesures de Séries Chronologiques'),
('Data_set','OPG010.sql','En','OPG010 SanKey Series'),
('Data_set','OPG010.sql','Fr','Série SanKey'),
('Labels','Parameter','En','Parameters'),
('Labels','Parameters','Fr','Paramètres'),
('Labels','Graph','En','Graph'),
('Labels','Graph','Fr','Graphique'),
('Labels','Graphing App','En','Graphing App'),
('Labels','Graphing App','Fr','Application Graphique'),
('Labels','Hierarchy','En','Hierarchy'),
('Labels','Hierarchy','Fr','Hiérarchie'),
('Labels','Level Filter','En','Level Filter'),
('Labels','Level Filter','Fr','Filtre de Niveau'),
('Labels','Specific Item','En','Specific Item'),
('Labels','Specific Item','Fr','Article Spécifique'),
('Labels','Select','En','Select'),
('Labels','Select','Fr','Sélectionner'),
('Labels','Timeframe','En','TimeFrame'),
('Labels','Timeframe','Fr','Plage de Temps'),
('Labels','Year','En','Year'),
('Labels','Year','Fr','Année'),
('Labels','Fiscal Year','En','Fiscal Year'),
('Labels','Fiscal Year','Fr','Exercice fiscal'),
('Labels','Mont','En','Mont'),
('Labels','Mont','Fr','Mois'),
('Labels','Quarter','En','Quarter'),
('Labels','Quarter','Fr','Trimestre'),
('Labels','Graph Type','En','Graph Type'),
('Labels','Graph Type','Fr','Type de Graphique'),
('Labels','X-Axis','En','X-Axis'),
('Labels','X-Axis','Fr','Axe X'),
('Labels','Y-Axis','En','Y-Axis'),
('Labels','Y-Axis','Fr','Axe Y'),
('Labels','Line','En','Line'),
('Labels','Line','Fr','Linéaire'),
('Labels','Bar','En','Bar'),
('Labels','Bar','Fr','Barres'),
('Labels','Scatter','En','Scatter'),
('Labels','Scatter','Fr','Dispersion'),
('Labels','Partial Period','En','Partial Period'),
('Labels','Partial Period','Fr','Période Partielle'),
('Labels','Graph Options','En','Graph Options'),
('Labels','Graph Options','Fr','Options de Graphique'),
('Labels','Revert','En','Revert'),
('Labels','Revert','Fr','Revenir'),
('Labels','To Top','En','To Top'),
('Labels','To Top','Fr','Au Début'),
('Labels','Graph All in Dropdown','En','Graph All in Dropdown'),
('Labels','Graph All in Dropdown','Fr','Graphique Tout dans la Liste Déroulante'),
('Labels','Time','En','Time'),
('Labels','Time','Fr','Temps'),
('Labels','Variable Names','En','Variable Names'),
('Labels','Variable Names','Fr','Noms de Variables'),
('Labels','Children','En','Children'),
('Labels','Children','Fr','Enfants'),
('Labels','H1','Fr','Niveau d''Organisation 1 (Haut)'),
('Labels','H1','En','Organization Level 1 (Top)'),
('Labels','H2','En','Organization Level 2'),
('Labels','H2','Fr','Niveau d''Organisation 2'),
('Labels','H3','En','Organization Level 3'),
('Labels','H3','Fr','Niveau d''Organisation 3'),
('Labels','H4','En','Organization Level 4'),
('Labels','H4','Fr','Niveau d''Organisation 4'),
('Labels','H5','En','Organization Level 5'),
('Labels','H5','Fr','Niveau d''Organisation 5'),
('Labels','H6','En','Organization'),
('Labels','H6','Fr','Organisation'),
('Labels','TRUE','En','TRUE'),
('Labels','TRUE','Fr','Vrai'),
('Labels','FALSE','En','FALSE'),
('Labels','FALSE','Fr','Faux'),
('Labels','New','En','New'),
('Labels','New','Fr','Nouveau'),
('Labels','View','En','View'),
('Labels','View','Fr','Vue'),
('Labels','Data','En','Data'),
('Labels','Data','Fr','Données'),
('Labels','Customize','En','Customize'),
('Labels','Customize','Fr','Personnaliser'),
('Labels','Enter Graph Title','En','Enter Graph Title'),
('Labels','Enter Graph Title','Fr','Entrez le Titre du Graphique'),
('Labels','Hierarchy Selection''s Children','En','Hierarchy Selection''s Children'),
('Labels','Hierarchy Selection''s Children','Fr','Enfants de la Sélection de Hiérarchie'),
('Labels','Table','En','Table'),
('Labels','Table','Fr','Tableau'),
('Labels','Hierarchy One Name','En','Hierarchy One Name'),
('Labels','Hierarchy One Name','Fr','Hiérarchie un Nom'),
('Labels','Variable Name','En','Document Type'),
('Labels','Variable Name','Fr','Nom de Variable'),
('Labels','Variable Name Qualifier','En','Document Type Qualifier'),
('Labels','Variable Name Qualifier','Fr','Qualificateur de Nom de Variable'),
('Labels','Variable Name Sub Qualifier','En','Document Type Sub Qualifier'),
('Labels','Variable Name Sub Qualifier','Fr','Sous-Qualificateur de Nom de Variable'),
('Labels','Date of Event','En','Date of Event'),
('Labels','Date of Event','Fr','Date de l''évènement'),
('Labels','Calendar Entry Type','En','Calendar Entry Type'),
('Labels','Calendar Entry Type','Fr','Type d''entrée d''Agenda'),
('Labels','Year of Event','En','Year of Event'),
('Labels','Year of Event','Fr','Année de l''événement'),
('Labels','Month of Event','En','Month of Event'),
('Labels','Month of Event','Fr','Mois de l''événement'),
('Labels','Week of Event','En','Week of Event'),
('Labels','Week of Event','Fr','Semaine d''événement'),
('Labels','Fiscal Year of Event','En','Fiscal Year of Event'),
('Labels','Fiscal Year of Event','Fr','Année Financière de l''événement'),
('Labels','Fiscal Quarter','En','Fiscal Quarter'),
('Labels','Fiscal Quarter','Fr','Trimestre Fiscal'),
('Labels','Fiscal Month of Event','En','Fiscal Month of Event'),
('Labels','Fiscal Month of Event','Fr','Mois Fiscal de l''événement'),
('Labels','Fiscal Week of Event','En','Fiscal Week of Event'),
('Labels','Fiscal Week of Event','Fr','Semaine Fiscale de l''événement'),
('Labels','Julian Day','En','Julian Day'),
('Labels','Julian Day','Fr','Julian Day'),
('Labels','Activity Event Id','En','Activity Event Id'),
('Labels','Activity Event Id','Fr','ID d''événement d''Activité'),
('Labels','Measure Value','En','Measure Value'),
('Labels','Measure Value','Fr','Mesurer la Valeur'),
('Labels','Measure Type','En','Measure Type'),
('Labels','Measure Type','Fr','Type de Mesure'),
('Labels','Toggle Columns','En','Toggle Columns'),
('Labels','Toggle Columns','Fr','Basculer les Colonnes'),
('Labels','Box Plot','En','Box Plot'),
('Labels','Box Plot','Fr','Boîte à Moustaches'),
('Labels','Show Data Points','En','Show Data Points'),
('Labels','Show Data Points','Fr','Afficher les Points de Données'),
('Labels','Horizontal','En','Horizontal'),
('Labels','Horizontal','Fr','Horizontal'),
('Labels','Vertical','En','Vertical'),
('Labels','Vertical','Fr','Vertical'),
('Labels','Graphed Variables','En','Graphed Variables'),
('Labels','Graphed Variables','Fr','Variables Graphiques'),
('Labels','Median','En','Median'),
('Labels','Median','Fr','Médiane'),
('Labels','Min','En','Min'),
('Labels','Min','Fr','Min'),
('Labels','Max','En','Max'),
('Labels','Max','Fr','Max'),
('Labels','Distribution','En','Distribution'),
('Labels','Distribution','Fr','Distribution'),
('Labels','Calendar Type','En','Calendar Type'),
('Labels','Calendar Type','Fr','Type de Calendrier'),
('Labels','Gregorian','En','Gregorian'),
('Labels','Gregorian','Fr','Grégorien'),
('Labels','Fiscal','En','Fiscal'),
('Labels','Fiscal','Fr','Fiscal'),
('Labels','All-Time (Monthly)','En','All-Time (Monthly)'),
('Labels','All-Time (Monthly)','Fr','Tous les Temps (Mensuel)'),
('Labels','Last','En','Last'),
('Labels','Last','Fr','Dernière'),
('Labels','Select Range','En','Select Range'),
('Labels','Select Range','Fr','Sélectionnez la Gamme'),
('Labels','Year(s)','En','Year(s)'),
('Labels','Year(s)','Fr','Année(s)'),
('Labels','Month(s)','En','Month(s)'),
('Labels','Month(s)','Fr','Mois'),
('Labels','Quarter(s)','En','Quarter(s)'),
('Labels','Quarter(s)','Fr','Trimestre(s)'),
('Labels','Week(s)','En','Week(s)'),
('Labels','Week(s)','Fr','Semaine(s)'),
('Labels','Available','En','Available'),
('Labels','Available','Fr','Valide'),
('Labels','Week','En','Week'),
('Labels','Week','Fr','Semaine'),
('Labels','Root''s Children','En','Root''s Children'),
('Labels','Root''s Children','Fr','Les Enfants de Root'),
('Labels','Back','En','Back'),
('Labels','Back','Fr','Arrière'),
('Labels','Top','En','Top'),
('Labels','Top','Fr','Haut'),
('Labels','Axis Measure','En','Axis Measure'),
('Labels','Axis Measure','Fr','Mesure d''Axe'),
('Labels','Graph Orientation','En','Graph Orientation'),
('Labels','Graph Orientation','Fr','Orientation du Graphique'),
('Labels','# of Rows','En','# of Rows'),
('Labels','# of Rows','Fr','# de Ros'),
('Labels','How to Filter the Table','En','How to Filter the Table'),
('Labels','How to Filter the Table','Fr','Comment Filtrer le Tableau'),
('Labels','How to Hide Columns','En','How to Hide Columns'),
('Labels','How to Hide Columns','Fr','Comment Masquer les Colonnes'),
('Labels','Date','En','Date'),
('Labels','Date','Fr','Date'),
('Labels','Root','En','Root'),
('Labels','Root','Fr','l'' Origine'),
('Labels','Group By','En','Group By'),
('Labels','Group By','Fr','Par Groupe'),
('Labels','Children of','En','Children of'),
('Labels','Children of','Fr','Les Enfants de'),
('Labels','Tab','En','Tab'),
('Labels','Tab','Fr','Onglet'),
('Labels','Graphs','En','Graphs'),
('Labels','Graphs','Fr','Graphiques'),
('Labels','Save the graph','En','Save the graph:'),
('Labels','Save the graph','Fr','Enregistrer le graphique:'),
('Labels','Select a saved graph','En','Select a saved graph:'),
('Labels','Select a saved graph','Fr','Sélectionnez un graphique enregistré:'),
('Labels','Delete a saved graph','En','Delete a saved graph:'),
('Labels','Delete a saved graph','Fr','Supprimer un graphique enregistré:'),
('Labels','Save Graph','En','Save Graph'),
('Labels','Save Graph','Fr','Enregistrer le graphique'),
('Labels','Confirm Delete','En','Confirm Delete'),
('Labels','Confirm Delete','Fr','Confirmation de la Suppression'),
('Labels','Enter Dashboard Title','En','Enter Dashboard Title'),
('Labels','Enter Dashboard Title','Fr','Entrez le titre du tableau de bord'),
('Labels','Save Dashboard','En','Save Dashboard'),
('Labels','Save Dashboard','Fr','Enregistrez le tableau de bord'),
('Labels','Delete a saved dashboard','En','Delete a saved dashboard'),
('Labels','Delete a saved dashboard','Fr','Supprimer un tableau de bord enregistré'),
('Labels','Dashboards require a title to be saved','En','Dashboards require a title to be saved'),
('Labels','Dashboards require a title to be saved','Fr','Les tableaux de bord nécessitent un titre pour être enregistrés'),
('Labels','Graph All Siblings','En','Graph All Siblings'),
('Labels','Graph All Siblings','Fr','Graphique de Tous les fratries'),
('Labels','No Data Found','En','No Data Found'),
('Labels','No Data Found','Fr','Aucune Donnée Disponible'),
('Labels','No Data Specified','En','No Data Specified'),
('Labels','No Data Specified','Fr','Aucune Donnée Spécifiée'),
('Labels','Data Accessed on','En','Data Accessed on'),
('Labels','Data Accessed on','Fr','Données Consultées le '),
('Labels','Data Set','En','Data Set'),
('Labels','Data Set','Fr','Base de Données'),
('Labels','Graphs require a title to be saved','En','Graphs require a title to be saved'),
('Labels','Graphs require a title to be saved','Fr','Les graphiques nécessitent un titre pour être enregistrés'),
('Labels','The graph has been saved','En','The graph has been saved'),
('Labels','The graph has been saved','Fr','Le graphique a été enregistré'),
('Labels','A saved graph with this title already exists','En','A saved graph with this title already exists'),
('Labels','A saved graph with this title already exists','Fr','Un graphique enregistré avec ce titre existe déjà'),
('Labels','The dashboard has been saved','En','The dashboard has been saved'),
('Labels','The dashboard has been saved','Fr','Le tableau de bord a été enregistré'),
('Labels','Dashboard must not be empty','En','Dashboard must not be empty'),
('Labels','Dashboard must not be empty','Fr','Le tableau de bord ne doit pas être vide'),
('Labels','A saved dashboard with this title already exists','En','A saved dashboard with this title already exists'),
('Labels','A saved dashboard with this title already exists','Fr','Un tableau de bord enregistré avec ce titre existe déjà'),
('Labels','Saved graphs already exist for','En','Saved graphs already exist for'),
('Labels','Saved graphs already exist for','Fr','Des graphiques enregistrés existent déjà pour'),
('Labels','Select a saved dashboard','En','Select a saved dashboard'),
('Labels','Select a saved dashboard','Fr','Sélectionnez un tableau de bord enregistré'),
('Labels','Cancel save attempt','En','Cancel save attempt'),
('Labels','Cancel save attempt','Fr','Annuler la tentative de sauvegarde'),
('Labels','Overwrite dashboard','En','Overwrite dashboard'),
('Labels','Overwrite dashboard','Fr','Écraser le tableau de bord'),
('Labels','and the graph','En','and the graph'),
('Labels','and the graph','Fr','et le graphique'),
('Labels','and the graphs','En','and the graphs'),
('Labels','and the graphs','Fr','et les graphiques'),
('Labels','Overwrite graph','En','Overwrite graph'),
('Labels','Overwrite graph','Fr','Écraser le graphique'),
('Labels','Overwrite graphs','En','Overwrite graphs'),
('Labels','Overwrite graphs','Fr','Écraser les graphiques'),
('Labels','Reset dashboard - all unsaved changes will be lost','En','Reset dashboard - all unsaved changes will be lost'),
('Labels','Reset dashboard - all unsaved changes will be lost','Fr','Réinitialiser le tableau de bord - toutes les modifications non enregistrées seront perdues'),
('Labels','Cancel reset attempt','En','Cancel reset attempt'),
('Labels','Cancel reset attempt','Fr','Annuler la tentative de réinitialisation'),
('Labels','Sankey','En','Sankey'),
('Labels','Sankey','Fr','Fr: Sankey'),
('Labels','In6','En','150+'),
('Labels','In5','En','121-150'),
('Labels','In4','En','91-120'),
('Labels','In3','En','61-90'),
('Labels','In2','En','31-60'),
('Labels','In1','En','LT 31'),
('Labels','End6','En','Cpltd 150+'),
('Labels','End5','En','Cpltd 121-150'),
('Labels','End4','En','Cpltd 91-120'),
('Labels','End3','En','Cpltd 61-90'),
('Labels','End2','En','Cpltd 31-60'),
('Labels','End1','En','Cpltd LT 31'),
('Labels','Out6','En','Cont 150+'),
('Labels','Out5','En','Cont 121-150'),
('Labels','Out4','En','Cont 91-120'),
('Labels','Out3','En','Cont 61-90'),
('Labels','Out2','En','Cont 31-60'),
('Labels','Out1','En','Cont LT 31'),
('Labels','In6_Long','En','Outstanding > 150 days'),
('Labels','In6_Long','Fr','Fr: Outstanding > 150 days'),
('Labels','In5_Long','En','Outstanding 121 - 150 days'),
('Labels','In5_Long','Fr','Fr: Outstanding 121 - 150 days'),
('Labels','In4_Long','En','Outstanding 91 - 120 days'),
('Labels','In4_Long','Fr','Fr: Outstanding 91 - 120 days'),
('Labels','In3_Long','En','Outstanding 61 - 90 days'),
('Labels','In3_Long','Fr','Fr: Outstanding 61 - 90 days'),
('Labels','In2_Long','En','Outstanding 31 - 60 days'),
('Labels','In2_Long','Fr','Fr: Outstanding 31 - 60 days'),
('Labels','In1_Long','En','Outstanding < 31 days'),
('Labels','In1_Long','Fr','Fr: Outstanding < 31 days'),
('Labels','End6_Long','En','Completed > 150 days'),
('Labels','End6_Long','Fr','Fr: Completed > 150 days'),
('Labels','End5_Long','En','Completed 121 - 150 days'),
('Labels','End5_Long','Fr','Fr: Completed 121 - 150 days'),
('Labels','End4_Long','Fr','Fr: Completed 91 - 120 days'),
('Labels','End3_Long','En','Completed 61 - 90 days'),
('Labels','End3_Long','Fr','Fr: Completed 61 - 90 days'),
('Labels','End2_Long','En','Completed 31 - 60 days'),
('Labels','End2_Long','Fr','Fr: Completed 31 - 60 days'),
('Labels','End1_Long','En','Completed < 31 days'),
('Labels','End1_Long','Fr','Fr: Completed < 31 days'),
('Labels','New_Long','En','New in last 30 days'),
('Labels','New_Long','Fr','Fr: New in last 30 days'),
('Labels','Out6_Long','En','Continued In-Process > 150 days'),
('Labels','Out6_Long','Fr','Fr: Continued In-Process > 150 days'),
('Labels','Out5_Long','En','Continued In-Process 121 - 150 days'),
('Labels','Out5_Long','Fr','Fr: Continued In-Process 121 - 150 days'),
('Labels','Out4_Long','En','Continued In-Process 91 - 120 days'),
('Labels','Out4_Long','Fr','Fr: Continued In-Process 91 - 120 days'),
('Labels','Out3_Long','En','Continued In-Process 61 - 90 days'),
('Labels','Out3_Long','Fr','Fr: Continued In-Process 61 - 90 days'),
('Labels','Out2_Long','En','Continued In-Process 31 - 60 days'),
('Labels','Out2_Long','Fr','Fr: Continued In-Process 31 - 60 days'),
('Labels','Out1_Long','En','Continued In-Process < 31 days'),
('Labels','Out1_Long','Fr','Fr: Continued In-Process < 31 days'),
('Labels','End','En','Cpltd'),
('Labels','End','Fr','Fr: Cpltd'),
('Labels','End_Long','En','Completed'),
('Labels','End_Long','Fr','Fr: Completed');

go
---when we update it from a space to underscore it gives key errors
/*
UPDATE [dbo].[OP_Ref]
SET    ref_value = REPLACE(ref_value, ' ', '_')
WHERE  ref_value LIKE '%[ ]%'
go*/

IF OBJECT_ID('dbo.reftable') IS NOT NULL
    PRINT   'REFTABLE Procedure Exists'

ELSE
	BEGIN
		EXEC('
    Create Proc dbo.reftable

    as
	BEGIN
    Select * From [dbo].[OP_Ref]
		END')
	END
    go

/*
exec dbo.reftable
go*/